-- Active: 1670107173962@@127.0.0.1@3306@c1461857_api

-- 1- Sincronario 
  -- 
  DELETE FROM `sis-app_nav` WHERE `esq` = 'sincronario';
  --
  -- 1- Libros
    DELETE FROM `sis-app_nav` WHERE `esq` = 'sincronario' AND `cab` = 'libro';
    
    -- la tierra en ascenso
    DELETE FROM `sis-app_nav` WHERE `esq` = 'sincronario' AND `cab` = 'libro' AND `art` = 'tierra_en_ascenso'; INSERT INTO `sis-app_nav` VALUES 
      ('sincronario','libro','tierra_en_ascenso','01','Parte 1. La Geomancia es a la Historia, lo que la Gramática es al Lenguaje. Dos ensayos introductorios.'),
      ('sincronario','libro','tierra_en_ascenso','01-01','Las raíces de la Unidad. La Geomancia y el Orden Mundial'),
      ('sincronario','libro','tierra_en_ascenso','01-02','De la Geomancia a la Holonomia. El descubrimiento del Banco Psi, la Investigación de la Historia. La Educación Holonómica. Arte, Ciencia y Orden Sagrado.'),
      ('sincronario','libro','tierra_en_ascenso','02','Parte 2. Los Mapas'),
      ('sincronario','libro','tierra_en_ascenso','02-01','La Naturaleza se Presenta a si Misma.'),
      ('sincronario','libro','tierra_en_ascenso','02-01-00','Mapas I: Preludio. El Código, La Clave, El Modelo.'),
      ('sincronario','libro','tierra_en_ascenso','02-01-01','Mapa 1: La Matriz del Banco Psi.'),
      ('sincronario','libro','tierra_en_ascenso','02-01-02','Mapa 2: La triple Configuración Binaria- El Código y la Clave'),
      ('sincronario','libro','tierra_en_ascenso','02-01-03','Mapa 3: Modelos de campos resonantes, derivados del a Triple Configuración Binaria.'),
      ('sincronario','libro','tierra_en_ascenso','02-01-04','Mapa 4: La Matriz del Banco Psi como resonancia Binaria de los Cinturones de Radiación.'),
      ('sincronario','libro','tierra_en_ascenso','02-01-05','Mapa 5: Carta del flujo Geomántico y el Modelo de Anillos Psi Evolucionados.'),
      ('sincronario','libro','tierra_en_ascenso','02-01-06','Mapa 6: Cerebro Holonómico y Demostración de la Circulación Psi, dentro del campo Electromagnético.'),
      ('sincronario','libro','tierra_en_ascenso','02-01-07','Mapa 7: El I-Ching como Descripción de la Matriz del Espacio-Tiempo Holonómico y del Código Genético.'),
      ('sincronario','libro','tierra_en_ascenso','02-01-08','Mapa 8: Ejemplo de Transmisión Psi casual. El Cuadrado Mágico de Ben Franklin.'),
      ('sincronario','libro','tierra_en_ascenso','02-01-09','Mapa 9: El Tzolkin, la Versión Maya del Calendario Sagrado.'),
      ('sincronario','libro','tierra_en_ascenso','02-02','El hombre Aprende de la Naturaleza.'),
      ('sincronario','libro','tierra_en_ascenso','02-02-00','Mapas II: Preludio. Del Afinamiento Primario a la elaboración Psicosensorial.'),
      ('sincronario','libro','tierra_en_ascenso','02-02-01','Mapa 10: El Movimiento Rítmico del Calendario Sagrado como patrón de Afinamiento Primario.'),
      ('sincronario','libro','tierra_en_ascenso','02-02-02','Mapa 11: La Camisa del Shaman y el Árbol de la Vida. Interpretación del Hombre y la Naturaleza.'),
      ('sincronario','libro','tierra_en_ascenso','02-02-03','Mapa 12: Templete de Afinamiento Aboriginal.'),
      ('sincronario','libro','tierra_en_ascenso','02-02-04','Mapa 13: Afinamiento Primario y Geomancia.'),
      ('sincronario','libro','tierra_en_ascenso','02-02-05','Mapa 14: El Modelo holonómico de Conocimiento.'),
      ('sincronario','libro','tierra_en_ascenso','02-02-06','Mapa 15: El Mapa de campo Sinestetico o una Historia de los Sentidos.'),
      ('sincronario','libro','tierra_en_ascenso','02-02-07','Mapa 16: Onda Retroalimentadora Psicogenetica'),
      ('sincronario','libro','tierra_en_ascenso','02-03','El Hombre Transforma la Naturaleza'),
      ('sincronario','libro','tierra_en_ascenso','02-03-00','Mapas III: Preludio. De la Historia, la Armonía y la Recolección Holonómica.'),
      ('sincronario','libro','tierra_en_ascenso','02-03-01','Mapa 17: El pulso Binario de la Historia.'),
      ('sincronario','libro','tierra_en_ascenso','02-03-02','Mapa 18: La Matriz Holonómica del Espacio-Tiempo de la Historia Global y el Pulso Binario del Desarrollo Psicocultural.'),
      ('sincronario','libro','tierra_en_ascenso','02-03-03','Mapa 19: Pulso Binario del Desarrollo Psicocultural.'),
      ('sincronario','libro','tierra_en_ascenso','02-03-04','Mapa 20: Placas Tectónicas mostrando El Surgimiento de los Pulsos/ Puntos de la Civilización Global.'),
      ('sincronario','libro','tierra_en_ascenso','02-03-05','Mapa 21: Los 7 Prístinos Pulsos de Civilización.'),
      ('sincronario','libro','tierra_en_ascenso','02-03-06','Mapa 22: La Civilización Global, El Flujo Geocronológico: La Octava.'),
      ('sincronario','libro','tierra_en_ascenso','02-03-07','Mapa 23: El Flujo Geocronológico :La Clave Cromática.'),
      ('sincronario','libro','tierra_en_ascenso','02-03-08','Mapa 24: Placas Tectónicas y la corriente de civilización con las placas de Memoria Estacionales del Banco Psi.'),
      ('sincronario','libro','tierra_en_ascenso','02-03-09','Mapa 25: Un Mapa del Mundo Posthieratico mostrando las cuatro placas del Banco Psi y las 8 Divisiones Estacionales.'),
      ('sincronario','libro','tierra_en_ascenso','02-03-10','Mapa 26: Flujo clave Civilizacional Hierático del Banco Psi.'),
      ('sincronario','libro','tierra_en_ascenso','02-03-11','Mapa 27: Carta Flujo Geocronológica Psthieratico del Banco Psi.'),
      ('sincronario','libro','tierra_en_ascenso','02-03-12','Mapa 28: Campo Magnético de la Tierra.'),
      ('sincronario','libro','tierra_en_ascenso','02-04','La Naturaleza Evalúa la Transformación del Hombre.'),
      ('sincronario','libro','tierra_en_ascenso','02-04-00','Mapas IV: Preludio. Psi y el Código de la Historia.'),
      ('sincronario','libro','tierra_en_ascenso','02-04-01','Mapa 29: El Banco Psi Mostrando los 4 cuadrantes, 8 placas de Memoria Estacionales y 24 Membranas Nimboideas Psionicas.'),
      ('sincronario','libro','tierra_en_ascenso','02-04-02','Mapa 30: El Ciclo de Manchas Solares Generando las Auroras y la Actividad del Banco Psi como Código Calendarico Sagrado.'),
      ('sincronario','libro','tierra_en_ascenso','02-04-03','Mapa 31: Ciclo Binario de manchas Solares Manifiesto como Matriz Calendarica Bipolar del Banco Psi.'),
      ('sincronario','libro','tierra_en_ascenso','02-04-04','Mapa 32: Decodificacion de Banco Psi. El Cuadrado Mágico de 8 de Ben Franklin como Pulso de 260 y el Calendario Sagrado Maya.'),
      ('sincronario','libro','tierra_en_ascenso','02-04-05','Mapa 33: El Patrón Flujo de la Matriz Psi como el Templete de la Transformación Psicocultural Demostran-do los 8 Estadios de la Recolección Holonómica.'),
      ('sincronario','libro','tierra_en_ascenso','02-04-06','Mapa 34: El Cuerpo Calloso de la Historia y el Templete Binario Radiosónico.'),
      ('sincronario','libro','tierra_en_ascenso','02-04-07','Mapa 35: El Código de la Historia como la secuencia de la Transformación Biopsíquica (64 Estadios)a través de los 8 Estadios de la Recolección Holonómica.'),
      ('sincronario','libro','tierra_en_ascenso','02-04-08','Mapa 36: El Patrón del Campo Holonómico : 64 en secuencia Numérica , Anotación Maya.'),
      ('sincronario','libro','tierra_en_ascenso','02-04-09','Mapa 37: La Trama del Banco Psi como el Código de la Historia en la secuencia de la Columna Mística.'),
      ('sincronario','libro','tierra_en_ascenso','02-04-10','Mapa 38: La Trama del Banco Psi como Patrón Matriz para el Arquetipo de la Historia como Mito: La ser-piente Emplumada Arco Iris (Quetzalcoalt / Kukulkan).'),
      ('sincronario','libro','tierra_en_ascenso','02-05','Síntesis del Hombre y la Naturaleza.'),
      ('sincronario','libro','tierra_en_ascenso','02-05-00','Mapas V: Preludio. Ciencia Antigua, Magia Futura.'),
      ('sincronario','libro','tierra_en_ascenso','02-05-01','Mapa 39: Patrón del campo Holonómico: Arreglo de 8, Pulso de 260.'),
      ('sincronario','libro','tierra_en_ascenso','02-05-02','Mapa 40: Patrón del Campo Holonómico: Modelo primario del campo resonante como las Galaxias Gi-roscópicas.'),
      ('sincronario','libro','tierra_en_ascenso','02-05-03','Mapa 41: El Campo Psi como la Matriz de la Visión.'),
      ('sincronario','libro','tierra_en_ascenso','02-05-04','Mapa 42: La trama del Banco Psi y la Urdimbre Holonómica.'),
      ('sincronario','libro','tierra_en_ascenso','02-05-05','Mapa 43: La Clave del flujo del Banco Psi: 2 Templetes, 4 Placas de la Columna, 8 Placas Estacionales, 24 Membranas Nimboideas (...).'),
      ('sincronario','libro','tierra_en_ascenso','02-05-06','Mapa 44: La Matriz Psi como el Templete radiosónico y el Templete Radiosónico como el Templo del Hom-bre, mostrando los 5 Centros de Activación Biopsiquica.'),
      ('sincronario','libro','tierra_en_ascenso','02-05-07','Mapa 45: Carta de Activación Cromocelular Psicogenética.'),
      ('sincronario','libro','tierra_en_ascenso','02-05-08','Mapa 46: Trama del Banco Psi: Código Cromático.'),
      ('sincronario','libro','tierra_en_ascenso','02-05-09','Mapa 47: Las Cuatro Casas del Arco Iris del Sol, los Cuatro Ríos de la Vida.'),
      ('sincronario','libro','tierra_en_ascenso','02-05-10','Mapa 48: El Patrón de Campo Holonómico :Configuración del Circuito Polar Binario de 16 Partes.'),
      ('sincronario','libro','tierra_en_ascenso','02-06','Conclusión: Para Cruzar la Gran Agua de la Historia.'),
      ('sincronario','libro','tierra_en_ascenso','02-06-00','Mapas VI, Un Preludio al Mapa 49'),
      ('sincronario','libro','tierra_en_ascenso','02-06-01','Mapa 49: Revolución, Postludio.'),
      ('sincronario','libro','tierra_en_ascenso','02-06-02','Mapa 50: Sinergía y Holonomia.'),
      ('sincronario','libro','tierra_en_ascenso','03','Apéndices'),
      ('sincronario','libro','tierra_en_ascenso','03-01','Reporte del Arte Planetario.'),
      ('sincronario','libro','tierra_en_ascenso','03-02','Los Cuadrados Mágicos de Ben Franklin y la Polaridad Cruzada.'),
      ('sincronario','libro','tierra_en_ascenso','03-03','Templete Formula Holonómica.')
    ;
    -- el factor maya
    DELETE FROM `sis-app_nav` WHERE `esq` = 'sincronario' AND `cab` = 'libro' AND `art` = 'factor_maya'; INSERT INTO `sis-app_nav` VALUES 
      ('sincronario','libro','factor_maya','00','Introducción. El misterio de los mayas: La ciencia trasciende'),
      ('sincronario','libro','factor_maya','01','Mi búsqueda'),
        ('sincronario','libro','factor_maya','01-01','1953: Inicios, la visión'),
        ('sincronario','libro','factor_maya','01-02','1964: Primer Visita, el Universo de Quetzalcoatl'),
        ('sincronario','libro','factor_maya','01-03','1966: Las Puertas de Percepción'),
        ('sincronario','libro','factor_maya','01-04','1968: Segunda Visita, el Monte Albán'),
        ('sincronario','libro','factor_maya','01-05','1974: El Tzolkin y La visión Transformadora'),
        ('sincronario','libro','factor_maya','01-06','1976: Tercer Visita, el Territorio Maya'),
        ('sincronario','libro','factor_maya','01-07','1981: El Arte Planetario'),
        ('sincronario','libro','factor_maya','01-08','1983: Radiogénesis y la Tierra en Ascenso'),
        ('sincronario','libro','factor_maya','01-09','1985: La Astrología y el Factor Maya'),
        ('sincronario','libro','factor_maya','01-10','1986: Cuarta Visita, El tzolkin y la Adoración al Sol'),
      ('sincronario','libro','factor_maya','02','Los Mayas, Adivinos de la Armonía'),  
        ('sincronario','libro','factor_maya','02-01','Arqueología: Cronología y marco Teórico'),
        ('sincronario','libro','factor_maya','02-02','Historia: Cosmología y Ciencia Galáctica'),
        ('sincronario','libro','factor_maya','02-03','Vision Galáctica: Hunab Ku y Kuxan Suum'),
        ('sincronario','libro','factor_maya','02-04','Resonancia: Información y Armonía'),
        ('sincronario','libro','factor_maya','02-05','Paradigma: Ciencia Mental y Sincronización Galáctica'),
        ('sincronario','libro','factor_maya','02-06','Objetivo: la Transducción Resonante'),
        ('sincronario','libro','factor_maya','02-07','Medio: el Viaje Espacial y los códigos del ADN'),
        ('sincronario','libro','factor_maya','02-08','Tzolkin: la Sincronización del Sol con otros mundos'),
        ('sincronario','libro','factor_maya','02-09','La Misión de los Mayas en la Tierra'),
      ('sincronario','libro','factor_maya','03','Los Maestros Galácticos y los Número del Destino'),
        ('sincronario','libro','factor_maya','03-01','El código: 13 números y 20 signos'),
        ('sincronario','libro','factor_maya','03-02','La cuenta: Función cualititiva del numero'),			
        ('sincronario','libro','factor_maya','03-03','La matriz: Secuencias Radiales'),
        ('sincronario','libro','factor_maya','03-04','El Tzolkin: Constante del tiempo Galáctico'),
        ('sincronario','libro','factor_maya','03-05','El modelo: Rayo de Sincronización Galáctica'),
        ('sincronario','libro','factor_maya','03-06','El sistema: Ciclos del Tiempo Armónico'),
        ('sincronario','libro','factor_maya','03-07','La Historia: 1° Oleada galáctica de los Mayas'),
        ('sincronario','libro','factor_maya','03-08','La Historia: 2° Oleada galáctica de los Mayas'),
        ('sincronario','libro','factor_maya','03-09','La Leyenda: Pakal Votan, el Agente Galáctico'),
        ('sincronario','libro','factor_maya','03-10','Conclusión: el Éxodo y la profecía'),
      ('sincronario','libro','factor_maya','04','El Telar Maya, el Módulo Armónico revelado'),
        ('sincronario','libro','factor_maya','04-01','El origen y la misión del Tzolkin'),
          ('sincronario','libro','factor_maya','04-01-01','Relaciones entre el Tzolkin y el I-Ching'),
          ('sincronario','libro','factor_maya','04-01-02','El código Galáctico y el Código Genético'),
          ('sincronario','libro','factor_maya','04-01-03','Tzolkin: la constante del circuito galáctico'),
        ('sincronario','libro','factor_maya','04-02','El Telar Maya y los hilos del destino'),
          ('sincronario','libro','factor_maya','04-02-01','La estructura resonante de los símbolos'),
          ('sincronario','libro','factor_maya','04-02-02','El cuerpo de luz y su estructura resonante'),
        ('sincronario','libro','factor_maya','04-03','La estructura galáctica resonante de 52 unidades'),
          ('sincronario','libro','factor_maya','04-03-01','Los 13 juegos de 4 unidades'),
          ('sincronario','libro','factor_maya','04-03-02','Los Números de Intervalo'),
        ('sincronario','libro','factor_maya','04-04','El sistema operativo de símbolos numéricos'),
          ('sincronario','libro','factor_maya','04-04-01','Los 13 números'),
            ('sincronario','libro','factor_maya','04-04-01-01','Como rayos de pulsación'),
            ('sincronario','libro','factor_maya','04-04-01-02','Combinados por simetría especular'),
          ('sincronario','libro','factor_maya','04-04-02','Los 20 símbolos'),
            ('sincronario','libro','factor_maya','04-04-02-01','Como rangos de frecuencia'),
            ('sincronario','libro','factor_maya','04-04-02-02','Como símbolos ideográficos'),
            ('sincronario','libro','factor_maya','04-04-02-03','La Matriz direccional'),
            ('sincronario','libro','factor_maya','04-04-02-04','Las 3 etapas en el desarrollo del Ser'),
            ('sincronario','libro','factor_maya','04-04-02-05','Las 5 familias cíclicas'),
            ('sincronario','libro','factor_maya','04-04-02-06','Las 4 etapas evolutivas de la mente'),
          ('sincronario','libro','factor_maya','04-04-03','Las 260 unidades'),
            ('sincronario','libro','factor_maya','04-04-03-01','Las 4 estaciones galácticas'),          
            ('sincronario','libro','factor_maya','04-04-03-02','El módulo armónico como un holoescaner'),
      ('sincronario','libro','factor_maya','05','Historia y Sistema Solar, la Visión Galáctica'),
        ('sincronario','libro','factor_maya','05-01','Los cuerpos de Luz y el Banco-Psi'),
        ('sincronario','libro','factor_maya','05-02','El Gran ciclo de 5.200 tun'),
        ('sincronario','libro','factor_maya','05-03','Composición del Rayo de Sincronización-G.'),
        ('sincronario','libro','factor_maya','05-04','Los 13 baktunes del Tiempo Galáctico'),
        ('sincronario','libro','factor_maya','05-05','El proceso planetario en el sistema solar'),
          ('sincronario','libro','factor_maya','05-05-01','Los ciclos de la respiración solar'),
          ('sincronario','libro','factor_maya','05-05-02','El papel de los planetas'),
          ('sincronario','libro','factor_maya','05-05-03','El proceso evolutivo solar-interplanetario'),
        ('sincronario','libro','factor_maya','05-06','La onda armónica de la historia'),
          ('sincronario','libro','factor_maya','05-06-01','Los signos como capacitadores resonantes'),        
          ('sincronario','libro','factor_maya','05-06-02','El cambio cíclico del modelo morfogenético'),
          ('sincronario','libro','factor_maya','05-06-03','El sub-ciclo de 20 katunes por baktun'),        
        ('sincronario','libro','factor_maya','05-07','Los 20 ciclos AHAU'),
          ('sincronario','libro','factor_maya','05-07-01','Descripciones mítico-poéticas'),
          ('sincronario','libro','factor_maya','05-07-02','La superposición con los ciclos KATUN'),
        ('sincronario','libro','factor_maya','05-08','El cuerpo de luz planetario'),
        ('sincronario','libro','factor_maya','05-08-01','Las 52 unidades del telar maya'),
        ('sincronario','libro','factor_maya','05-08-02','Sincronización de doble sentido direccional'),
      ('sincronario','libro','factor_maya','06','El Final del Ciclo, Sincronización con el más allá'),
        ('sincronario','libro','factor_maya','06-01','Contexto actual: el Armagedón'),      
        ('sincronario','libro','factor_maya','06-02','Baktún 12: los 2 últimos ciclos Ahau'),
        ('sincronario','libro','factor_maya','06-03','Baktún 12: los 20 katunes'),
          ('sincronario','libro','factor_maya','06-03-01','Katun 00: 1.618 - 1.638 D.C.'),
          ('sincronario','libro','factor_maya','06-03-02','Katun 01: 1.638 - 1.658 D.C.'),
          ('sincronario','libro','factor_maya','06-03-03','Katun 02: 1.658 - 1.677 D.C.'),
          ('sincronario','libro','factor_maya','06-03-04','Katun 03: 1.677 - 1.697 D.C.'),
          ('sincronario','libro','factor_maya','06-03-05','Katun 04: 1.697 - 1.717 D.C.'),
          ('sincronario','libro','factor_maya','06-03-06','Katun 05: 1.717 - 1.736 D.C.'),
          ('sincronario','libro','factor_maya','06-03-07','Katun 06: 1.736 - 1.756 D.C.'),
          ('sincronario','libro','factor_maya','06-03-08','Katun 07: 1.756 - 1.776 D.C.'),
          ('sincronario','libro','factor_maya','06-03-09','Katun 08: 1.776 - 1.796 D.C.'),
          ('sincronario','libro','factor_maya','06-03-10','Katun 09: 1.796 - 1.815 D.C.'),
          ('sincronario','libro','factor_maya','06-03-11','Katun 10: 1.815 - 1.835 D.C.'),
          ('sincronario','libro','factor_maya','06-03-12','Katun 11: 1.835 - 1.855 D.C.'),
          ('sincronario','libro','factor_maya','06-03-13','Katun 12: 1.855 - 1.874 D.C.'),
          ('sincronario','libro','factor_maya','06-03-14','Katun 13: 1.874 - 1.894 D.C.'),
          ('sincronario','libro','factor_maya','06-03-15','Katun 14: 1.894 - 1.914 D.C.'),
          ('sincronario','libro','factor_maya','06-03-16','Katun 15: 1.914 - 1.933 D.C.'),
          ('sincronario','libro','factor_maya','06-03-17','Katun 16: 1.933 - 1.953 D.C.'),
          ('sincronario','libro','factor_maya','06-03-18','Katun 17: 1.953 - 1.973 D.C.'),
          ('sincronario','libro','factor_maya','06-03-19','Katun 18: 1.973 - 1.992 D.C.'),
          ('sincronario','libro','factor_maya','06-03-20','Katun 19: 1.992 - 2.012 D.C.'),
          ('sincronario','libro','factor_maya','06-03-21','Katun 00: 2.012 D.C.'),
        ('sincronario','libro','factor_maya','06-04','La discordancia resonante'),
        ('sincronario','libro','factor_maya','06-05','La sincronización crítica'),
      ('sincronario','libro','factor_maya','07','Tecnología y Transformación'),
        ('sincronario','libro','factor_maya','07-01','El desarrollo tecnológico en la espiritualidad'),
          ('sincronario','libro','factor_maya','07-01-01','La ecuación tecnológica y los cambios en el ADN'),
          ('sincronario','libro','factor_maya','07-01-02','El proceso generado por el rayo de sincronización'),
          ('sincronario','libro','factor_maya','07-01-03','La luz y la vida: El tzolkin con la estructura del ADN'),
          ('sincronario','libro','factor_maya','07-01-04','Distinciones entre el mito y la historia'),
        ('sincronario','libro','factor_maya','07-02','El paso de la Tierra por el Rayo de Sincronización'),
          ('sincronario','libro','factor_maya','07-02-01','Cambio de paradigma: la tecnología se convierte en transformación'),
          ('sincronario','libro','factor_maya','07-02-02','La convergencia armónica: el ultimo paso hacia la sincronización galáctica'),
        ('sincronario','libro','factor_maya','07-03','El cuerpo de luz y su aplicación con el ADN mediante el tablero resonante - tzolkin -'),
          ('sincronario','libro','factor_maya','07-03-01','Los 13 campos del tzolkin y la función del ADN en la historia-tecnología'),
          ('sincronario','libro','factor_maya','07-03-02','La función de la tecnología en la estructura del código ADN'),
          ('sincronario','libro','factor_maya','07-03-03','Las 64 unidades del código genético, el i-ching y el cuadrado mágico del 8'),
        ('sincronario','libro','factor_maya','07-04','El papel de los mayas en el proceso de sincronización'),
          ('sincronario','libro','factor_maya','07-04-01','Otras pistas en el sistema solar'),
          ('sincronario','libro','factor_maya','07-04-02','El regreso de Pacal Votan en la convergecia armónica'),
          ('sincronario','libro','factor_maya','07-04-03','El último paso: los recuerdos, la nueva percepción y la campaña por la Tierra'),
          ('sincronario','libro','factor_maya','07-04-04','Impresiones icónicas: los guerreros del Shambhala'),        
      ('sincronario','libro','factor_maya','08','La próxima Era Solar'),
        ('sincronario','libro','factor_maya','08-01','Dimensiones de consciencia y la aparición del humano en el proceso planetario'),
          ('sincronario','libro','factor_maya','08-01-01','Comienzos del ciclo y la primer aparición del reino de Shambala'),
          ('sincronario','libro','factor_maya','08-01-02','Del culto solar planetario a la industrialización global'),
          ('sincronario','libro','factor_maya','08-01-03','La era del Materialismo: punto cúlmine en el rayo de sincronización'),
        ('sincronario','libro','factor_maya','08-02','El mar electromagnético del entorno, y el circuito bio-electromagnético del humano'),
          ('sincronario','libro','factor_maya','08-02-01','Los elementos del circuito y las corrientes de información'),
          ('sincronario','libro','factor_maya','08-02-02','La activación del cuerpo de luz'),
        ('sincronario','libro','factor_maya','08-03','El tzolkin como modelo del campo del cuerpo luminoso'),        
          ('sincronario','libro','factor_maya','08-03-01','Las 13 articulaciones principales y los 20 dedos en las manos y los pies'),
          ('sincronario','libro','factor_maya','08-03-02','Los órganos de los Sentidos y los puntos de actividad Galáctica'),
          ('sincronario','libro','factor_maya','08-03-03','Las enfermedades de la era indusrtial y la medicina bio-electromagnética'),
        ('sincronario','libro','factor_maya','08-04','Cosmovisión del cuerpo de luz: la resonancia del humano con la tierra'),
          ('sincronario','libro','factor_maya','08-04-01','El disfrute de los sentidos como desbloqueo natural'),
          ('sincronario','libro','factor_maya','08-04-02','El proceso de Resonancia psico-sensoria'),
          ('sincronario','libro','factor_maya','08-04-03','El Código galáctico informativo de la magnetósfera terrestre'),
          ('sincronario','libro','factor_maya','08-04-04','Liberaciones de energía resonante en el campo terrestre y humano'),
        ('sincronario','libro','factor_maya','08-05','La nueva casa de los sentidos en la próxima era solar'),
          ('sincronario','libro','factor_maya','08-05-01','Aspectos científicos generales'),
          ('sincronario','libro','factor_maya','08-05-02','Estilo de vida creativo y espiritual'),
          ('sincronario','libro','factor_maya','08-05-03','Conexion universal y organización autónoma'),
          ('sincronario','libro','factor_maya','08-05-04','Últimos pasos hacia la transformación'),
      ('sincronario','libro','factor_maya','09','Manual del paradigma resonante'),
        ('sincronario','libro','factor_maya','09-01','Glosario de términos'),
        ('sincronario','libro','factor_maya','09-02','Conceptos claves de los mayas'),
      ('sincronario','libro','factor_maya','10','El Armónico Sistema Numérico de los mayas'),
        ('sincronario','libro','factor_maya','10-01','Progresiones Binarias'),
        ('sincronario','libro','factor_maya','10-02','Armónicos de Luz y de onda'),
        ('sincronario','libro','factor_maya','10-03','El Sistema matemático'),
      ('sincronario','libro','factor_maya','11','Sumplementos'),
        ('sincronario','libro','factor_maya','11-01','Números direccionales y números radiales'),	
        ('sincronario','libro','factor_maya','11-02','Factores y Fractales Maya'),	
        ('sincronario','libro','factor_maya','11-03','Armónicos del Calendario'),	
        ('sincronario','libro','factor_maya','11-04','Números Armónicos'),	
        ('sincronario','libro','factor_maya','11-05','Ciclo de 52 años y el calendario circular diario')	
    ;
    -- el encantamiento del sueño
    DELETE FROM `sis-app_nav` WHERE `esq` = 'sincronario' AND `cab` = 'libro' AND `art` = 'encantamiento_del_sueño'; INSERT INTO `sis-app_nav` VALUES 
      ('sincronario','libro','encantamiento_del_sueño','01','Parte 1. El Géneses'),
        ('sincronario','libro','encantamiento_del_sueño','01-01','Génsis del Encantamiento del Sueño'),
        ('sincronario','libro','encantamiento_del_sueño','01-02','El Don'),
      ('sincronario','libro','encantamiento_del_sueño','02','Parte 2. Oráculo del Destino del Encantamiento del Sueño'),
        ('sincronario','libro','encantamiento_del_sueño','02-01','La Misión del Encantamiento del Sueño de la Nave del Tiempo Tierra 2.013'),
          ('sincronario','libro','encantamiento_del_sueño','02-01-01','Reparto y Trama'),
          ('sincronario','libro','encantamiento_del_sueño','02-01-02','Antecedentes'),
          ('sincronario','libro','encantamiento_del_sueño','02-01-03','Resultado'),
        ('sincronario','libro','encantamiento_del_sueño','02-02','Cómo jugar y entrar en el oráculo del Tiempo Galáctico'),
          ('sincronario','libro','encantamiento_del_sueño','02-02-01','Oráculo del Encantamiento del Sueño: Partes'),
            ('sincronario','libro','encantamiento_del_sueño','02-02-01-01','1. Brujula Galáctica'),
            ('sincronario','libro','encantamiento_del_sueño','02-02-01-01-01','Funda de la Brújula'),
            ('sincronario','libro','encantamiento_del_sueño','02-02-01-01-02','Tarjeta de Referencia Rápida'),
            ('sincronario','libro','encantamiento_del_sueño','02-02-01-01-03','Brújula Galáctica'),
            ('sincronario','libro','encantamiento_del_sueño','02-02-01-01-04','Instrucciones'),
            ('sincronario','libro','encantamiento_del_sueño','02-02-01-01-05','Índice Armónico'),
            ('sincronario','libro','encantamiento_del_sueño','02-02-01-01-06','Guía del Oráculo'),
            ('sincronario','libro','encantamiento_del_sueño','02-02-01-02','2. Cubo de Color y Fichas'),
            ('sincronario','libro','encantamiento_del_sueño','02-02-01-03','3. Tablero del Oráculo'),
            ('sincronario','libro','encantamiento_del_sueño','02-02-01-04','4. Tablero del Viaje'),
            ('sincronario','libro','encantamiento_del_sueño','02-02-01-05','5. Textos del Encantamiento del Sueño'),
          ('sincronario','libro','encantamiento_del_sueño','02-02-02','Oráculo del Destino del Encantamiento del Sueño: Cómo jugar'),
        ('sincronario','libro','encantamiento_del_sueño','02-03','Reglas del Juego del Encantamiento del Sueño'),
          ('sincronario','libro','encantamiento_del_sueño','02-03-01','Firma Galáctica: el Holón, el kin Planetario y el Ego'),
          ('sincronario','libro','encantamiento_del_sueño','02-03-02','Ley del Kin.'),
          ('sincronario','libro','encantamiento_del_sueño','02-03-03','Jugando el Oráculo del Encantamiento del Sueño'),
          ('sincronario','libro','encantamiento_del_sueño','02-03-04','Conociendo el Átomo del Tiempo Cromático: El Cubo de Color'),
          ('sincronario','libro','encantamiento_del_sueño','02-03-05','Las fichas de los 20 Sellos Solares'),
          ('sincronario','libro','encantamiento_del_sueño','02-03-06','Guía del Oráculo del Encantamiento del Sueño: colocar y leer el Oráculo'),
            ('sincronario','libro','encantamiento_del_sueño','02-03-06-01','Claves de lectura'),
            ('sincronario','libro','encantamiento_del_sueño','02-03-06-02','Tonos Galácticos'),
            ('sincronario','libro','encantamiento_del_sueño','02-03-06-03','Ley de los pares antípodas y ocultos'),
            ('sincronario','libro','encantamiento_del_sueño','02-03-06-04','Ley de las Parejas Antípodas'),
            ('sincronario','libro','encantamiento_del_sueño','02-03-06-05','Ley de las Parejas Ocultas y los Cuartetos'),
            ('sincronario','libro','encantamiento_del_sueño','02-03-06-06','Parejas Análogas'),
          ('sincronario','libro','encantamiento_del_sueño','02-03-07','Índice Armónico.'),
          ('sincronario','libro','encantamiento_del_sueño','02-03-08','Sendero del Destino de 52 años'),
          ('sincronario','libro','encantamiento_del_sueño','02-03-09','Calendario Perpetuo de 13 Lunas'),
          ('sincronario','libro','encantamiento_del_sueño','02-03-10','Tablero de Viaje del Mapa del Tiempo: el Giro Galáctico de 260 Kin'),
          ('sincronario','libro','encantamiento_del_sueño','02-03-11','Polaridad Radial'),
        ('sincronario','libro','encantamiento_del_sueño','02-04','Unidades de Medida'),
        ('sincronario','libro','encantamiento_del_sueño','02-05','Glosario del Encantamiento del Sueño'),
      ('sincronario','libro','encantamiento_del_sueño','03','Parte 3. Índice del Oráculo del Encantamiento del Sueño'),
        ('sincronario','libro','encantamiento_del_sueño','03-01','Oráculo del Destino de las Cuatro Razas Raíz Cósmicas'),
        ('sincronario','libro','encantamiento_del_sueño','03-02','Índice del Génesis de Clanes: Colocación Cromática'),
        ('sincronario','libro','encantamiento_del_sueño','03-03','Índice del Génesis Planetario: Código Solar-Galáctico 0-19'),
        ('sincronario','libro','encantamiento_del_sueño','03-04','Índice de Razas Raíz: Colocación Armónica'),
        ('sincronario','libro','encantamiento_del_sueño','03-05','Índice de Células del Tiempo: Colocación Armónica'),
        ('sincronario','libro','encantamiento_del_sueño','03-06','Índice del Génesis de los Castillos: Génesis del Encantamiento del Sueño'),
        ('sincronario','libro','encantamiento_del_sueño','03-07','Holón del Planeta: La Nave Tiempo Tierra 2.013'),
        ('sincronario','libro','encantamiento_del_sueño','03-08','Holón Humano'),
        ('sincronario','libro','encantamiento_del_sueño','03-09','Quinta Fuerza: El Poder de los Trece Tonos Galácticos'),
        ('sincronario','libro','encantamiento_del_sueño','03-10','Onda Encantada: Qué es'),
        ('sincronario','libro','encantamiento_del_sueño','03-11','Calendario Perpetuo de 13 Lunas y 13 Tonos Galácticos de la onda encantada'),
        ('sincronario','libro','encantamiento_del_sueño','03-12','Onda Encantada de la Aventura'),
        ('sincronario','libro','encantamiento_del_sueño','03-13','Código Púlsar'),
        ('sincronario','libro','encantamiento_del_sueño','03-14','Cuenta atrás de 26 años de la Nave Tiempo Tierra 2.013'),
        ('sincronario','libro','encantamiento_del_sueño','03-15','Escudo de la Quinta Fuerza Galáctica'),
        ('sincronario','libro','encantamiento_del_sueño','03-16','Kin Polar y el Giro Espectral'),
        ('sincronario','libro','encantamiento_del_sueño','03-17','Libro del Kin'),
      ('sincronario','libro','encantamiento_del_sueño','04','Parte 4. El Libro del Kin'),
        ('sincronario','libro','encantamiento_del_sueño','04-01','Castillo Rojo Este del Girar (Arm 1-13)'),
          ('sincronario','libro','encantamiento_del_sueño','04-01-01','Dragón Rojo'),
          ('sincronario','libro','encantamiento_del_sueño','04-01-02','Mago Blanco'),
          ('sincronario','libro','encantamiento_del_sueño','04-01-03','Mano Azul'),
          ('sincronario','libro','encantamiento_del_sueño','04-01-04','Sol Amarillo'),
        ('sincronario','libro','encantamiento_del_sueño','04-02','Castillo Blanco Norte del Cruzar (Arm 14-26)'),
          ('sincronario','libro','encantamiento_del_sueño','04-02-01','Caminante del Cielo Rojo'),
          ('sincronario','libro','encantamiento_del_sueño','04-02-02','Enlazador de Mundos Blanco'),
          ('sincronario','libro','encantamiento_del_sueño','04-02-03','Tormenta Azul'),
          ('sincronario','libro','encantamiento_del_sueño','04-02-04','Humano Amarillo'),
        ('sincronario','libro','encantamiento_del_sueño','04-03','Castillo Azul Oeste del Quemar (Arm 27-39)'),
          ('sincronario','libro','encantamiento_del_sueño','04-03-01','Serpiente Roja'),
          ('sincronario','libro','encantamiento_del_sueño','04-03-02','Espejo Blanco'),
          ('sincronario','libro','encantamiento_del_sueño','04-03-03','Mono Azul'),
          ('sincronario','libro','encantamiento_del_sueño','04-03-04','Semilla Amarilla'),
        ('sincronario','libro','encantamiento_del_sueño','04-04','Castillo Amarillo Sur del Dar (Arm 40-52)'),
          ('sincronario','libro','encantamiento_del_sueño','04-04-01','Tierra Roja'),
          ('sincronario','libro','encantamiento_del_sueño','04-04-02','Perro Blanco'),
          ('sincronario','libro','encantamiento_del_sueño','04-04-03','Noche Azul'),
          ('sincronario','libro','encantamiento_del_sueño','04-04-04','Guerrero Amarillo'),
        ('sincronario','libro','encantamiento_del_sueño','04-05','Castillo Verde Central del Encantar (Arm 53-65)'),
          ('sincronario','libro','encantamiento_del_sueño','04-05-01','Luna Roja'),
          ('sincronario','libro','encantamiento_del_sueño','04-05-02','Viento Blanco'),
          ('sincronario','libro','encantamiento_del_sueño','04-05-03','Águila Azul'),
          ('sincronario','libro','encantamiento_del_sueño','04-05-04','Estrella Amarilla'),    
      ('sincronario','libro','encantamiento_del_sueño','05','Apéndice I: La nave del Tiempo Tierra 2013'),
        ('sincronario','libro','encantamiento_del_sueño','05-01','El Arte Planetario del Tiempo Galáctico'),
        ('sincronario','libro','encantamiento_del_sueño','05-02','Glosario de Términos'),
      ('sincronario','libro','encantamiento_del_sueño','06','Componentes del Juego'),
        ('sincronario','libro','encantamiento_del_sueño','06-01','Brújula Galáctica'),
        ('sincronario','libro','encantamiento_del_sueño','06-02','Cubo de Color'),
        ('sincronario','libro','encantamiento_del_sueño','06-03','Tablero del Oráculo'),
        ('sincronario','libro','encantamiento_del_sueño','06-04','Tablero del Viaje')		
    ;
    -- las 13 lunas en movimiento
    DELETE FROM `sis-app_nav` WHERE `esq` = 'sincronario' AND `cab` = 'libro' AND `art` = 'lunas_en_movimiento'; INSERT INTO `sis-app_nav` VALUES 
      ('sincronario','libro','lunas_en_movimiento','01','Una Época De Apocalipsis: El calendario Gregoriano Desenmascarado Una Postdata de 13 Lunas al Factor Maya'),
        ('sincronario','libro','lunas_en_movimiento','01-01','Pensando sobre lo Impensable'),
        ('sincronario','libro','lunas_en_movimiento','01-02','Lunas, Mayas y el Calendario de 13 Lunas'),
        ('sincronario','libro','lunas_en_movimiento','01-03','Romper la Barrera: Liberarse del Encantamiento del Sueño de la Historia'),
      ('sincronario','libro','lunas_en_movimiento','02','13 Lunas en Movimiento: Punto de partida de los Kin Planetarios del Calendario de 13 Lunas'),
        ('sincronario','libro','lunas_en_movimiento','02-01','El Calendario de 13 Lunas y la Naturaleza del Tiempo'),
        ('sincronario','libro','lunas_en_movimiento','02-02','EL Calendario de 13 Lunas: Un Vehículo de Liberación'),
        ('sincronario','libro','lunas_en_movimiento','02-03','Para Convertirte en un Kin Planetario, Sigue las Trece Lunas'),
        ('sincronario','libro','lunas_en_movimiento','02-04','El Calendario de 13 Lunas y la Onda Encantada del Servicio Planetario'),
          ('sincronario','libro','lunas_en_movimiento','02-04-01','Pulsares Dimensionales'),
          ('sincronario','libro','lunas_en_movimiento','02-04-02','Pulsares Entonados'),
        ('sincronario','libro','lunas_en_movimiento','02-05','La Perfección Armónica de la Onda Encantada del Calendario de 13 Lunas'),
        ('sincronario','libro','lunas_en_movimiento','02-06','El Punto de Partida del Calendario'),
        ('sincronario','libro','lunas_en_movimiento','02-07','Entrando en la Corriente: Distribución de Cada Luna del Calendario'),
          ('sincronario','libro','lunas_en_movimiento','02-07-01','Fechas de las 13 lunas'),
          ('sincronario','libro','lunas_en_movimiento','02-07-02','Funciones de las 13 lunas'),
          ('sincronario','libro','lunas_en_movimiento','02-07-03','Los 7 Días por Semana'),
          ('sincronario','libro','lunas_en_movimiento','02-07-04','Las 4 Semanas por Luna'),
          ('sincronario','libro','lunas_en_movimiento','02-07-05','Los ciclos lunares'),
          ('sincronario','libro','lunas_en_movimiento','02-07-06','Las 13 posiciones diarias de la onda encantada'),
          ('sincronario','libro','lunas_en_movimiento','02-07-07','Los 5 castillos del giro galáctico'),
          ('sincronario','libro','lunas_en_movimiento','02-07-08','El tzolkin: código enzima galáctico'),
          ('sincronario','libro','lunas_en_movimiento','02-07-09','Notaciones del Sincronario'),
      ('sincronario','libro','lunas_en_movimiento','03','Almanaque Arturiano: Catálogo de los Ciclos Mayas del Encantamiento del Sueño'),
        ('sincronario','libro','lunas_en_movimiento','03-01','Nota Histórica'),
        ('sincronario','libro','lunas_en_movimiento','03-02','Ciclos Fractales del Tiempo Radial'),
          ('sincronario','libro','lunas_en_movimiento','03-02-01','Códigos'),
          ('sincronario','libro','lunas_en_movimiento','03-02-02','Ciclos menores'),
          ('sincronario','libro','lunas_en_movimiento','03-02-03','Ciclos mayores'),
          ('sincronario','libro','lunas_en_movimiento','03-02-04','Nota sobre ciclos mayas'),
      ('sincronario','libro','lunas_en_movimiento','04','La Tortuga de las Trece Lunas'),
        ('sincronario','libro','lunas_en_movimiento','04-01','Tortuga de las Trece Lunas en Movimiento'),
        ('sincronario','libro','lunas_en_movimiento','04-02','Trece Lunas: Un Sendero Soberano para caminar'),
        ('sincronario','libro','lunas_en_movimiento','04-03','Siguiendo la Onda Encantada hasta el 2013 DA'),
        ('sincronario','libro','lunas_en_movimiento','04-04','Isla Tortuga: El Viaje del Encantamiento del Sueño de la Nave Tiempo Tierra 2013'),
        ('sincronario','libro','lunas_en_movimiento','04-05','Las Cinco Familias Terrestres de la Nave Tiempo Tierra 2013 '),
      ('sincronario','libro','lunas_en_movimiento','05','Componentes'),
        ('sincronario','libro','lunas_en_movimiento','05-01','Colocacion Cromática'),
        ('sincronario','libro','lunas_en_movimiento','05-02','Colocacion Armónica'),
        ('sincronario','libro','lunas_en_movimiento','05-03','Holon Humano'),
        ('sincronario','libro','lunas_en_movimiento','05-04','Tzolkin'),
        ('sincronario','libro','lunas_en_movimiento','05-05','Sellos Solares')
    ;
    -- sonda de arcturus
    DELETE FROM `sis-app_nav` WHERE `esq` = 'sincronario' AND `cab` = 'libro' AND `art` = 'sonda_de_arcturus'; INSERT INTO `sis-app_nav` VALUES 
      ('sincronario','libro','sonda_de_arcturus','00','Introducción. Arcturo Recordado'),
      ('sincronario','libro','sonda_de_arcturus','01','Primera Parte: Lanzamiento de la Sonda'),
        ('sincronario','libro','sonda_de_arcturus','01-01','Preámbulo: Nosotros, los de Arcturo'),
        ('sincronario','libro','sonda_de_arcturus','01-02','Orígenes Heteróclitos de los Partícipes Secretos del Tiempo'),
        ('sincronario','libro','sonda_de_arcturus','01-03','Derrota Heteróclita de la Liga de Diez'),
        ('sincronario','libro','sonda_de_arcturus','01-04','Los Partícipes Secretos del Tiempo y el Descubrimiento del Código Púlsar'),
        ('sincronario','libro','sonda_de_arcturus','01-05','El Magnetismo Radial y el Arte Primigenio de la Gran Unificación'),
        ('sincronario','libro','sonda_de_arcturus','01-06','El Radión Estelar Central y la Federación Galáctica'),
        ('sincronario','libro','sonda_de_arcturus','01-07','Tres Cuerpos y el Viaje por el Tiempo: El Nacimiento de la Sonda de Arcturo'),
        ('sincronario','libro','sonda_de_arcturus','01-08','Telepatía y Gobierno Natural'),
        ('sincronario','libro','sonda_de_arcturus','01-09','El Dominio de Arcturo: La Sonda Excitada'),
        ('sincronario','libro','sonda_de_arcturus','01-10','El Sector de Velatropa o Zona Galáctica Experimental'),
        ('sincronario','libro','sonda_de_arcturus','01-11','Arcturo, la Estrella Pastora del Séptimo Poder'),
        ('sincronario','libro','sonda_de_arcturus','01-12','Procesiones del Conocimiento Sensorial'),
        ('sincronario','libro','sonda_de_arcturus','01-13','La Recompensa: Moldeado del Oráculo del Encantamiento del Sueño'),
        ('sincronario','libro','sonda_de_arcturus','01-14','Una Tabla Redonda del Escudo Galáctico Azul de la Magia'),
        ('sincronario','libro','sonda_de_arcturus','01-15','Memnosis: La Perdurabilidad Recordada'),
        ('sincronario','libro','sonda_de_arcturus','01-16','Relato de Merlín: Co-participación del Tiempo entre los Arboles de Procyon'),
        ('sincronario','libro','sonda_de_arcturus','01-17','Estrellas Gemelas y Tragedia en Alfa Centauro'),
        ('sincronario','libro','sonda_de_arcturus','01-18','Sirio Convoca la Vacuna: La Cepa de Lucifer'),
        ('sincronario','libro','sonda_de_arcturus','01-19','Los Engramas Planetarios que dejan su Marca en la Zuvuya'),
        ('sincronario','libro','sonda_de_arcturus','01-20','Obsesionados Homólogos de los Homóclitos'),
        ('sincronario','libro','sonda_de_arcturus','01-21','Perceval y la Dama del Lago: Escudo Masculino y Escudo Femenino'),
        ('sincronario','libro','sonda_de_arcturus','01-22','Domesticación de Planetas: Una Desviación de la Quinta Fuerza'),
        ('sincronario','libro','sonda_de_arcturus','01-23','Acerca de Perros y Ballenas: Universos Paralelos, Déjà Vus Múltiples'),
        ('sincronario','libro','sonda_de_arcturus','01-24','Regreso al Dragón: Fuente la Matriz'),
        ('sincronario','libro','sonda_de_arcturus','01-25','Los Mayores de la Corriente: Velatropa en Foco'),
        ('sincronario','libro','sonda_de_arcturus','01-26','Instalación de la Estación Intermedia AA'),
      ('sincronario','libro','sonda_de_arcturus','02','Segunda Parte: Recordando la Nave del Tiempo'),
        ('sincronario','libro','sonda_de_arcturus','02-01','Preguntas de la Intermedia'),
        ('sincronario','libro','sonda_de_arcturus','02-02','Informe de Arc-Tara: Muerte Oculta, Muerte Develada'),
        ('sincronario','libro','sonda_de_arcturus','02-03','Voz del Amo Estelar Kinich Ahau'),
        ('sincronario','libro','sonda_de_arcturus','02-04','El Ah K`al Balaam: Conocedor Uno de la Totalidad'),
        ('sincronario','libro','sonda_de_arcturus','02-05','El Holón Resonante Universal: Las Veinte Tribus del Tiempo'),
        ('sincronario','libro','sonda_de_arcturus','02-06','Radiados Bisexuados de Cinco Puntas: Engendramiento de las Tribus'),
        ('sincronario','libro','sonda_de_arcturus','02-07','Llegada de los Maya, Navegantes del Tiempo'),
        ('sincronario','libro','sonda_de_arcturus','02-08','Nacimiento de las Veinte Tribus: Historia Temprana de Kinich Ahau'),
        ('sincronario','libro','sonda_de_arcturus','02-09','Punto Final para las Guerras del Tiempo: La Historia Original de Maldek'),
        ('sincronario','libro','sonda_de_arcturus','02-10','Serpientes y Magos de Maldek: La Profecía de Merlín'),
        ('sincronario','libro','sonda_de_arcturus','02-11','Guerras del Tiempo: Lucifer Rastreado, Marte Recordado'),
        ('sincronario','libro','sonda_de_arcturus','02-12','Hijos de Memnosis'),
        ('sincronario','libro','sonda_de_arcturus','02-13','Un Diseño de Nave del Tiempo Dirigido por los Maya'),
        ('sincronario','libro','sonda_de_arcturus','02-14','La Larga Espera: Terra-Gaia Despertada'),
        ('sincronario','libro','sonda_de_arcturus','02-15','La Nave del Tiempo Ingresa en la Tierra: Camelot Desaparece'),
        ('sincronario','libro','sonda_de_arcturus','02-16','Ultima Maquinación de Lucifer: El Miedo Babilónico a la Muerte'),
        ('sincronario','libro','sonda_de_arcturus','02-17','Hacia Venus o Lucifer: Pacificación de las Proyecciones'),
        ('sincronario','libro','sonda_de_arcturus','02-18','La Dama Blanca de Heron Recuerda el Futuro'),
        ('sincronario','libro','sonda_de_arcturus','02-19','La Corporación de Atlantis: Mundo Mecanizado'),
        ('sincronario','libro','sonda_de_arcturus','02-20','Sembrar la Espora y Remontarse Nuevamente: Intervención Interdimensional'),
        ('sincronario','libro','sonda_de_arcturus','02-21','Jugando al Ajedrez Arcturiano: Créditos del Kin'),
        ('sincronario','libro','sonda_de_arcturus','02-22','Radiosónicos, por fin: Tocando el Acorde de la Quinta Fuerza'),
        ('sincronario','libro','sonda_de_arcturus','02-23','Epílogo y Prólogo: El Amor Cósmico es Despiadado'),
      ('sincronario','libro','sonda_de_arcturus','03','APÉNDICE'),
        ('sincronario','libro','sonda_de_arcturus','03-01','Breve tratado sobre la aplicación de la cosmología del púlsar'),
        ('sincronario','libro','sonda_de_arcturus','03-02','Armónicas del Púlsar'),
        ('sincronario','libro','sonda_de_arcturus','03-03','Las Bases Galácticas de la Electricidad'),
        ('sincronario','libro','sonda_de_arcturus','03-04','Implicancias y Aplicaciones'),
        ('sincronario','libro','sonda_de_arcturus','03-05','Resonancias Fractales'),
        ('sincronario','libro','sonda_de_arcturus','03-06','Líneas de Resonancia Telepática: 26 Tipos de Vértices del Púlsar'),
      ('sincronario','libro','sonda_de_arcturus','04','GLOSARIO')		
    ;  
    -- Un tratado del tiempo: visto desde su propia dimensión
    DELETE FROM `sis-app_nav` WHERE `esq` = 'sincronario' AND `cab` = 'libro' AND `art` = 'tratado_del_tiempo'; INSERT INTO `sis-app_nav` VALUES 
      ('sincronario','libro','tratado_del_tiempo','01','Introducción'),
      ('sincronario','libro','tratado_del_tiempo','02','Consideraciones'),
        ('sincronario','libro','tratado_del_tiempo','02-01','Pensando lo impensable'),
        ('sincronario','libro','tratado_del_tiempo','02-02','El Tiempo y la Biosfera: Más Allá del Nacionalismo'),
        ('sincronario','libro','tratado_del_tiempo','02-03','En Dios Confiamos: Respecto de la Falsa Religión el Tiempo es Dinero'),
        ('sincronario','libro','tratado_del_tiempo','02-04','De Lunas, Mayas y el Calendario de 13 Lunas'),        
      ('sincronario','libro','tratado_del_tiempo','03','I. Crítica'),
        ('sincronario','libro','tratado_del_tiempo','03-01','Descripción y Naturaleza del Problema'),        
        ('sincronario','libro','tratado_del_tiempo','03-02','Un Enfoque de los Sistemas Totales Planetarios'),
          ('sincronario','libro','tratado_del_tiempo','03-02-01','La Premisa Psicofísica'),
          ('sincronario','libro','tratado_del_tiempo','03-02-02','La Premisa Estética Universal'),
          ('sincronario','libro','tratado_del_tiempo','03-02-03','La Premisa Maya'),
          ('sincronario','libro','tratado_del_tiempo','03-02-04','La Premisa de los Sistemas Totales Planetarios'),
        ('sincronario','libro','tratado_del_tiempo','03-03','Descubrimiento de las Frecuencias de Tiempo 12:60 – 13:20'),
      ('sincronario','libro','tratado_del_tiempo','04','II. Principios'),
        ('sincronario','libro','tratado_del_tiempo','04-01','La Cuarta Dimensión: Cualidades y Naturaleza del Tiempo'),          
        ('sincronario','libro','tratado_del_tiempo','04-02','Principios Matemáticos del Tiempo Cuatridimensional'),
          ('sincronario','libro','tratado_del_tiempo','04-02-01','Matriz Radial'),
          ('sincronario','libro','tratado_del_tiempo','04-02-02','Fractales'),
          ('sincronario','libro','tratado_del_tiempo','04-02-03','Ratios'),
          ('sincronario','libro','tratado_del_tiempo','04-02-04','El Tetraedro y el Orden Tetraédrico'),
          ('sincronario','libro','tratado_del_tiempo','04-02-05','El Factor Más Uno'),
          ('sincronario','libro','tratado_del_tiempo','04-02-06','Resumen...'),
        ('sincronario','libro','tratado_del_tiempo','04-03','Pruebas y Demostraciones Matemáticas'),
          ('sincronario','libro','tratado_del_tiempo','04-03-01','El Código 0-19'),
          ('sincronario','libro','tratado_del_tiempo','04-03-02','La Onda Encantada'),
          ('sincronario','libro','tratado_del_tiempo','04-03-03','Los Púlsares'),
          ('sincronario','libro','tratado_del_tiempo','04-03-04','El Cubo de Color, Armónicas y Células del Tiempo'),
          ('sincronario','libro','tratado_del_tiempo','04-03-05','La Cromática o Quinto Entonado: El Tablero del Oráculo'),
          ('sincronario','libro','tratado_del_tiempo','04-03-06','Giro Galáctico: El Tablero de Viaje'),
          ('sincronario','libro','tratado_del_tiempo','04-03-07','Fractales Espectrales'),
          ('sincronario','libro','tratado_del_tiempo','04-03-08','La Brújula Galáctica'),
          ('sincronario','libro','tratado_del_tiempo','04-03-09','El Índice Armónico'),
          ('sincronario','libro','tratado_del_tiempo','04-03-10','La Péntada Binaria: Aplicaciones Especiales del Quinto Entonado'),
      ('sincronario','libro','tratado_del_tiempo','05','III. Síntesis y Aplicación: advenimiento de la Noosfera'),
        ('sincronario','libro','tratado_del_tiempo','05-01','Herramientas del Tiempo'),
        ('sincronario','libro','tratado_del_tiempo','05-02','La cronosfera planetaria'),
        ('sincronario','libro','tratado_del_tiempo','05-03','El advenimiento de la noosfera'),
        ('sincronario','libro','tratado_del_tiempo','05-04','Holones Planetario y Humano'),
        ('sincronario','libro','tratado_del_tiempo','05-05','Integracion final'),
      ('sincronario','libro','tratado_del_tiempo','06','IV. Apéndices'),
        ('sincronario','libro','tratado_del_tiempo','06-01','Práctica de la Igualdad Universal de Conciencia'),
        ('sincronario','libro','tratado_del_tiempo','06-02','La Transcensión Universal'),
        ('sincronario','libro','tratado_del_tiempo','06-03','Respecto a la Corporación Atlantis'),
        ('sincronario','libro','tratado_del_tiempo','06-04','Fórmula del Quinto Entonado: Transición a la Noosfera'),
      ('sincronario','libro','tratado_del_tiempo','07','V. POSTLUDIO: LA CONSTANTE DE LA BIOMASA, DE VERNADSKY, UNA ECUACIÓN EN EL TIEMPO'),
      ('sincronario','libro','tratado_del_tiempo','08','OTRA INFORMACION'),
      ('sincronario','libro','tratado_del_tiempo','08-01','Las 13 Cromáticas Fractales Espectrales'),
      ('sincronario','libro','tratado_del_tiempo','08-02','Las 73 Cromáticas Entonadas'),
      ('sincronario','libro','tratado_del_tiempo','08-03','Los 18 Vinales del ciclo de frecuencia solar del Haab')
    ;
    -- el telektonon
    DELETE FROM `sis-app_nav` WHERE `esq` = 'sincronario' AND `cab` = 'libro' AND `art` = 'telektonon'; INSERT INTO `sis-app_nav` VALUES 
      ('sincronario','libro','telektonon','01','Parte 1. Introducción'),
        ('sincronario','libro','telektonon','01-01','Telektonon: La Espada de la Luz'),
        ('sincronario','libro','telektonon','01-02','Tiempo y Telepatía'),
        ('sincronario','libro','telektonon','01-03','El Viaje en el Laberinto del Guerrero y el Cubo de la Ley'),
        ('sincronario','libro','telektonon','01-04','La Intersección Móvil del Tiempo'),
        ('sincronario','libro','telektonon','01-05','Telektonon y el Encantamiento del Sueño'),
        ('sincronario','libro','telektonon','01-06','Divina Revelación del Tiempo'),
        ('sincronario','libro','telektonon','01-07','Campos, Flujos y Circuitos'),
        ('sincronario','libro','telektonon','01-08','Tuvo por el que Habla el Espíritu de la Tierra'),
      ('sincronario','libro','telektonon','02','Parte 2. Cómo entrar y jugar al Telektonon'),
        ('sincronario','libro','telektonon','02-01','Entrando al Telektonon'),
        ('sincronario','libro','telektonon','02-02','El Manuscrito de los Amantes, las aventuras de Pacal Votan y Bolon Ik'),
        ('sincronario','libro','telektonon','02-03','El Tablero de juego del Telektonon'),
          ('sincronario','libro','telektonon','02-03-00','La Práctica Telepática de la Sincronometría'),
          ('sincronario','libro','telektonon','02-03-01','1° Nivel: Moviendo las 3 tortugas'),
          ('sincronario','libro','telektonon','02-03-02','2° Nivel: Calibrando el Movimiento Diario'),
          ('sincronario','libro','telektonon','02-03-03','3° Nivel: El juego de Cartas'),
          ('sincronario','libro','telektonon','02-03-04','4° Nivel: Juego del Oráculo'),
          ('sincronario','libro','telektonon','02-03-05','Sincronometría'),
            ('sincronario','libro','telektonon','02-03-05-01','Líneas de fuerza Verticales'),
            ('sincronario','libro','telektonon','02-03-05-02','Líneas de fuerza Horizontales'),
        ('sincronario','libro','telektonon','02-04','El Sarcófago de Pacal Votan'),
        ('sincronario','libro','telektonon','02-05','El juego de cartas del Manuscrito de los Amantes'),
          ('sincronario','libro','telektonon','02-05-01','El Cronómetro Diario Universal'),
          ('sincronario','libro','telektonon','02-05-02','Los Cuatro Libros de Sabiduría'),
          ('sincronario','libro','telektonon','02-05-02-01','Libro de las Siete Generaciones Perdidas'),
          ('sincronario','libro','telektonon','02-05-02-02','Libro del Tiempo Galáctico'),
          ('sincronario','libro','telektonon','02-05-02-03','Libro de la Forma Cósmica'),
          ('sincronario','libro','telektonon','02-05-02-04','Libro Telepático de la Redención de los Planetas Perdidos'),
          ('sincronario','libro','telektonon','02-05-03','El Esquema Diario de las Cartas'),
            ('sincronario','libro','telektonon','02-05-03-01','Posición Raíz'),
            ('sincronario','libro','telektonon','02-05-03-02','Posición Corazón'),
            ('sincronario','libro','telektonon','02-05-03-03','Posición Corona'),
            ('sincronario','libro','telektonon','02-05-03-04','Posición Torre'),
            ('sincronario','libro','telektonon','02-05-03-05','Ala Galáctica, posición diaria'),
            ('sincronario','libro','telektonon','02-05-03-06','Ala Solar, posición semanal'),
            ('sincronario','libro','telektonon','02-05-03-07','Ala Solar, posición diaria'),
        ('sincronario','libro','telektonon','02-06','Los Oráculos de las 7 Generaciones y los 7 años de Profecía'),
          ('sincronario','libro','telektonon','02-06-01','Los 7 años, los 7 anillos y los oráculos de las 7 generaciones'),
          ('sincronario','libro','telektonon','02-06-02','Los 7 Sellos de la Profecía'),
          ('sincronario','libro','telektonon','02-06-03','Reconstruyendo el Heptágono de la Mente'),
        ('sincronario','libro','telektonon','02-07','La Piedra Parlante de la Profecía'),
      ('sincronario','libro','telektonon','03','Parte 3. Glosario de Términos'),
      ('sincronario','libro','telektonon','04','Parte 4. Temas Finales'),
        ('sincronario','libro','telektonon','04-01','Los Dieciocho Vinales y el Vayeb'),
        ('sincronario','libro','telektonon','04-02','La Ley de Bode confirma el Telektonon'),
        ('sincronario','libro','telektonon','04-03','Calendario de 13 Lunas'),
        ('sincronario','libro','telektonon','04-04','20 Sellos Solares, Nombres y Números Códigos'),
        ('sincronario','libro','telektonon','04-05','Notación Galáctica'),
        ('sincronario','libro','telektonon','04-06','Reconocimientos'),
        ('sincronario','libro','telektonon','04-07','Una Historia de Amor')
    ;
    -- el proyecto rinri
    DELETE FROM `sis-app_nav` WHERE `esq` = 'sincronario' AND `cab` = 'libro' AND `art` = 'proyecto_rinri'; INSERT INTO `sis-app_nav` VALUES 
      ('sincronario','libro','proyecto_rinri','01','¿Qué es?'),
        ('sincronario','libro','proyecto_rinri','01-01','Introducción: un experimento científico llamado paz mundial'),
        ('sincronario','libro','proyecto_rinri','01-02','Exposición del problema y solución propuesta por el proyecto rinri'),
        ('sincronario','libro','proyecto_rinri','01-03','Descripción del experimento: girando el magneto invisible central del ser'),
          ('sincronario','libro','proyecto_rinri','01-03-01','Girando el Magneto Invisible Central del Ser. Cuatro Giros, Cuatro Años, Una Armónica Cósmica'),
          ('sincronario','libro','proyecto_rinri','01-03-02','Las Cuatro Placas del Banco Psi Mostrando la Activación Anual de las Unidades Psi Crono'),
          ('sincronario','libro','proyecto_rinri','01-03-03','La Red del Telektonon: Mostrando las Correspondencias Psi Crono, Telar Maya y Viaje del Cubo'),
        ('sincronario','libro','proyecto_rinri','01-04','El magneto invisible del ser: la vision total'),
      ('sincronario','libro','proyecto_rinri','02','¿Cómo Hacerlo?'),
        ('sincronario','libro','proyecto_rinri','02-01','1° paso: Las 73 cromaticas de la constante de la biomasa'),
          ('sincronario','libro','proyecto_rinri','02-01-01','Holón del Planeta'),
          ('sincronario','libro','proyecto_rinri','02-01-02','Holón Humano'),
        ('sincronario','libro','proyecto_rinri','02-02','2° paso: Correspondencias magneticas entre placas'),
          ('sincronario','libro','proyecto_rinri','02-02-01','Correspondencias Magnéticas entre los Años, Placas Psi, Estaciones y Colores'),
        ('sincronario','libro','proyecto_rinri','02-03','3° paso: Las unidades psi crono: siguiendo la pista al banco psi'),
        ('sincronario','libro','proyecto_rinri','02-04','4° paso: Correspondencias de la torre y el cubo entre el tablero del telektonon y las placas del banco psi'),
          ('sincronario','libro','proyecto_rinri','02-04-01','Correspondencias entre el Cuarteto Oculto y la Posición Torre del Telektonon'),
          ('sincronario','libro','proyecto_rinri','02-04-02','Instrucciones Especiales de la Visualización Telepática para los Días Torre'),
          ('sincronario','libro','proyecto_rinri','02-04-03','Las 16 Posiciones del Cubo y los 208 Pasos a la Torre del Mago Merlín'),
          ('sincronario','libro','proyecto_rinri','02-04-04','La Red del Telektonon: Mostrando las Correspondencias Psi Crono, Telar Maya y Viaje del Cubo'),
        ('sincronario','libro','proyecto_rinri','02-05','5° paso: Los siete plasmas radiales, los siete sellos y los siete años de la profecía. El heptágono de la mente'),
          ('sincronario','libro','proyecto_rinri','02-05-01','Los Siete Sellos, Siete Plasmas Radiales y sus Siete Funciones Anuales'),    
        ('sincronario','libro','proyecto_rinri','02-06','6° paso: Plantando el rayo cósmico: fases de aplicación'),
          ('sincronario','libro','proyecto_rinri','02-06-01','Fase 1: Lanzamiento de la Liberación del Plasma Radial'),
          ('sincronario','libro','proyecto_rinri','02-06-02','Fase 2 : Cambiando el Magneto, Construyendo el Cubo de la Ley'),
          ('sincronario','libro','proyecto_rinri','02-06-03','Subfase 1: 4° plasma, Kali '),
          ('sincronario','libro','proyecto_rinri','02-06-04','Subfase 2: 5° plasma, Alfa '),
          ('sincronario','libro','proyecto_rinri','02-06-05','Subfase 3: 6° plasma, Limi '),
          ('sincronario','libro','proyecto_rinri','02-06-06','Subfase 4: 7° plasma, Silio '),
        ('sincronario','libro','proyecto_rinri','02-07','7° paso: Lanzamiento del puente arcoiris circumpolar, manifestación del banco psi'),
        ('sincronario','libro','proyecto_rinri','02-08','Resumen de la meditación telepática diaria, instrucciones de la visualización y lista de herramientas'),
      ('sincronario','libro','proyecto_rinri','03','Viaje del Guerrero por el Cubo de la Ley'),
        ('sincronario','libro','proyecto_rinri','03-01','Una nota acerca del proyecto Rinri'),
        ('sincronario','libro','proyecto_rinri','03-02','Viaje del cubo del guerrero de 16 días'),
        ('sincronario','libro','proyecto_rinri','03-03','Afirmaciones'),       
        ('sincronario','libro','proyecto_rinri','03-04','Los 4 Principios guiadores'),
        ('sincronario','libro','proyecto_rinri','03-05','Telektonon: una historia de amor'),
      ('sincronario','libro','proyecto_rinri','04','Material Práctico'),
        ('sincronario','libro','proyecto_rinri','04-01','El proyecto rinri'),
        ('sincronario','libro','proyecto_rinri','04-02','Meditación diaria de la ley del tiempo'),
        ('sincronario','libro','proyecto_rinri','04-03','Afirmaciones diarias del cubo'),
        ('sincronario','libro','proyecto_rinri','04-04','Plantilla para rellenar el almanaque de los magos de la tierra'),
        ('sincronario','libro','proyecto_rinri','04-05','Armonicas - codones'),
        ('sincronario','libro','proyecto_rinri','04-06','El juego de la profecia'),
        ('sincronario','libro','proyecto_rinri','04-07','Runas del futhark antiguo'),
        ('sincronario','libro','proyecto_rinri','04-08','Banco psi'),
      ('sincronario','libro','proyecto_rinri','05','Portal del Tiempo')
    ;
    -- dinámicas del tiempo 
    DELETE FROM `sis-app_nav` WHERE `esq` = 'sincronario' AND `cab` = 'libro' AND `art` = 'dinamicas_del_tiempo'; INSERT INTO `sis-app_nav` VALUES 
      ('sincronario','libro','dinamicas_del_tiempo','00',''),
      ('sincronario','libro','dinamicas_del_tiempo','01','I.	ESTABLECIENDO LA NORMA'),
        ('sincronario','libro','dinamicas_del_tiempo','01-01','0. Postulados que Gobiernan la Dinámica del Tiempo en Relación a la Dinámica del Espacio'),
        ('sincronario','libro','dinamicas_del_tiempo','01-02','1. Postulados del Tiempo que Gobiernan el Propósito y Niveles de Consciencia de los Cuerpos en Evolución'),
        ('sincronario','libro','dinamicas_del_tiempo','01-03','2. Diferencias Variables en la Evolución en el Tiempo de las Diferentes Masas Estelares'),
        ('sincronario','libro','dinamicas_del_tiempo','01-04','3. La Naturaleza Holonómica del Cerebro Galáctico Incorporado en la Naturaleza Evolutiva de la Masa Estelar, Incluidos los Cuerpos Planetarios'),
        ('sincronario','libro','dinamicas_del_tiempo','01-05','4. El Cerebro Galáctico Incorporado en el Cuerpo en Evolución del Planeta Tierra'),
        ('sincronario','libro','dinamicas_del_tiempo','01-06','5. La Ley del Tiempo y la Transición Biosfera-Noosfera'),
      ('sincronario','libro','dinamicas_del_tiempo','01-07','6. Herramientas Humanas Cuatridimensionales para el Desarrollo de las Tecnologías Telepáticas Interdimensionales'),
      ('sincronario','libro','dinamicas_del_tiempo','02','II.	EJERCITANDO LA NORMA'),
        ('sincronario','libro','dinamicas_del_tiempo','02-01','7.	Uso de las Herramientas para Representar los Niveles de Incidencia de las Armónicas Celestes'),
        ('sincronario','libro','dinamicas_del_tiempo','02-02','8.	Yoga, Meditación y Teleportación Sensorial'),
        ('sincronario','libro','dinamicas_del_tiempo','02-03','9.	Naturaleza Hiperorgánica de la Evolución y el Advenimiento de la Era Psicozoica'),
        ('sincronario','libro','dinamicas_del_tiempo','02-04','10.	Principios de Reordenación Armónica del Orden Sincrónico'),
        ('sincronario','libro','dinamicas_del_tiempo','02-05','11.	Desarrollo de la Personalidad Secundaria Como Agente o Vehículo para el Viaje en el Tiempo'),
        ('sincronario','libro','dinamicas_del_tiempo','02-06','12.	Descripción de los Vehículos para el Viaje en el Tiempo'),
        ('sincronario','libro','dinamicas_del_tiempo','02-07','13.	Transporte en el Tiempo del Cuerpo Entero'),
      ('sincronario','libro','dinamicas_del_tiempo','03','III. PRACTICANDO LA NORMA COMO LA VIDA DE LAS FUNCIONES ANÁLOGAS SUPERIORES'),
        ('sincronario','libro','dinamicas_del_tiempo','03-01','14.	Excitación del Pulso Planetario y Estelar: Radión, Energía Radial, Matrices Radiales'),
        ('sincronario','libro','dinamicas_del_tiempo','03-02','15.	Incremento de la Incidencia de la Consciencia Subliminal como Efecto de la Retroalimentación de los Pulsos Planetario y Estelar'),
        ('sincronario','libro','dinamicas_del_tiempo','03-03','16.	Variedades y Etapas de la Excitación y Evolución Estelar'),
        ('sincronario','libro','dinamicas_del_tiempo','03-04','17.	Involucrando a la Federación Galáctica, y la Naturaleza de la Consciencia Post-Orgánica'),
        ('sincronario','libro','dinamicas_del_tiempo','03-05','18.	Viaje a los Universos Paralelos, o Visitas a Otros Cerebros Galácticos'),
        ('sincronario','libro','dinamicas_del_tiempo','03-06','19.	Dios'),
      ('sincronario','libro','dinamicas_del_tiempo','04','GRÁFICOS'),
        ('sincronario','libro','dinamicas_del_tiempo','04-01','Vehículo de Transporte del Cristal de Doble Terminación para la Teleportación Sensorial y Demostración del Viaje en el Tiempo del Poder del 19'),
        ('sincronario','libro','dinamicas_del_tiempo','04-02','Cerebro Galáctico: La Dinámica del Tiempo Mostrando la Evolución del Tiempo como Consciencia – T(E)=Arte')
    ;
    -- las 20 tablas del tiempo
    DELETE FROM `sis-app_nav` WHERE `esq` = 'sincronario' AND `cab` = 'libro' AND `art` = 'tablas_del_tiempo'; INSERT INTO `sis-app_nav` VALUES 
      ('sincronario','libro','tablas_del_tiempo','01','I. Prólogo: Entrada al Misterio'),
        ('sincronario','libro','tablas_del_tiempo','01-01','Enigma de la Piedra, de Pacal Votan.'),
        ('sincronario','libro','tablas_del_tiempo','01-02','Valum Votan, El Cerrador del Ciclo.'),
        ('sincronario','libro','tablas_del_tiempo','01-03','Recuperación del Plan Divino, Telektonon.'),
        ('sincronario','libro','tablas_del_tiempo','01-04','Concerniente al Samadhi de Pacal Votan, el Recuerdo de UR en la Tierra.'),
        ('sincronario','libro','tablas_del_tiempo','01-05','Concerniente a la Religión Universal en la Tierra.'),
        ('sincronario','libro','tablas_del_tiempo','01-06','El Aprendizaje Arcturiano de Valum Votan.'),
      ('sincronario','libro','tablas_del_tiempo','02','II. Las 20 Tablas de la Ley del Tiempo y el Libro de UR de la Vida Universal'),
        ('sincronario','libro','tablas_del_tiempo','02-01','Preámbulo.'),
        ('sincronario','libro','tablas_del_tiempo','02-02','Concerniente a las 20 Tablas de la Ley del Tiempo.'),
        ('sincronario','libro','tablas_del_tiempo','02-03','Índice de las 20 Tablas de la Ley del Tiempo y el Libro de UR de la Vida Universal'),
          ('sincronario','libro','tablas_del_tiempo','02-03-01','Las Cuatro Tablas de la Profecía'),
            ('sincronario','libro','tablas_del_tiempo','02-03-01-01','Tabla Uno de la Profecía. El Enigma de la Piedra, de Pacal Votan: Telektonon de 16 Años'),
            ('sincronario','libro','tablas_del_tiempo','02-03-01-02','Tabla Dos de la Profecía. El Tiempo de la Profecía: Los 26 Años de la Convergencia Armónica'),
            ('sincronario','libro','tablas_del_tiempo','02-03-01-03','Tabla Tres de la Profecía. El Portal del Tiempo: El Cubo de la Ley Interdimensional'),
            ('sincronario','libro','tablas_del_tiempo','02-03-01-04','Tabla Cuatro de la Profecía. Las 64 Runas de UR y los 64 Codones: Invocación del Manitú Planetario'),
          ('sincronario','libro','tablas_del_tiempo','02-03-02','Las Dieciséis Tablas de la Ley del Tiempo: Cubo de la Ley del Telektonon de Dieciséis Años, Génesis Galáctico Uso del Cronógrafo, Lectura de la Partitura'),
          ('sincronario','libro','tablas_del_tiempo','02-03-02-01','Cuadrante Estelar Este, Plano de la Mente, Tablas 1-4'),
            ('sincronario','libro','tablas_del_tiempo','02-03-02-01-01','Primera Tabla, 1997-98: Cuarto Rojo del Este, Cuadrante Estelar Este'),
            ('sincronario','libro','tablas_del_tiempo','02-03-02-01-02','Segunda Tabla, 1998-99: Cuarto Blanco del Norte, Cuadrante Estelar Este'),
            ('sincronario','libro','tablas_del_tiempo','02-03-02-01-03','Tercera Tabla, 1999-2000: Cuarto Azul del Oeste, Cuadrante Estelar Este'),
            ('sincronario','libro','tablas_del_tiempo','02-03-02-01-04','Cuarta Tabla, 2000-01: Cuarto Amarillo del Sur, Cuadrante Estelar Este'),
          ('sincronario','libro','tablas_del_tiempo','02-03-02-02','Cuadrante Estelar Norte, Plano del Espíritu, Tablas 5-8'),
            ('sincronario','libro','tablas_del_tiempo','02-03-02-02-01','Quinta Tabla, 2001-02: Cuarto Rojo de Este, Cuadrante Estelar Norte'),
            ('sincronario','libro','tablas_del_tiempo','02-03-02-02-02','Sexta Tabla, 2002-03: Cuarto Blanco del Norte, Cuadrante Estelar Norte'),
            ('sincronario','libro','tablas_del_tiempo','02-03-02-02-03','Séptima Tabla, 2003-04: Cuarto Azul del Oeste, Cuadrante Estelar Norte'),
            ('sincronario','libro','tablas_del_tiempo','02-03-02-02-04','Octava Tabla, 2004-05: Cuarto Amarillo del Sur, Cuadrante Estelar Norte'),
          ('sincronario','libro','tablas_del_tiempo','02-03-02-03','Cuadrante Estelar Oeste, Plano de la Voluntad, Tablas 9-12'),
            ('sincronario','libro','tablas_del_tiempo','02-03-02-03-01','Novena Tabla, 2005-06: Cuarto Rojo del Este, Cuadrante Estelar Oeste'),
            ('sincronario','libro','tablas_del_tiempo','02-03-02-03-02','Décima Tabla, 2006-07: Cuarto Blanco del Norte, Cuadrante Estelar Oeste    '),
            ('sincronario','libro','tablas_del_tiempo','02-03-02-03-03','Undécima Tabla, 2007-08: Cuarto Azul del Oeste, Cuadrante Estelar Oeste'),
            ('sincronario','libro','tablas_del_tiempo','02-03-02-03-04','Duodécima Tabla, 2008-09: Cuarto Amarillo del Sur, Cuadrante Estelar Oeste    '),
          ('sincronario','libro','tablas_del_tiempo','02-03-02-04','Cuadrante Estelar Sur, Fuente Divina, TEL-EK-TON-ON, Tablas 13-16'),
            ('sincronario','libro','tablas_del_tiempo','02-03-02-04-01','Decimotercera Tabla, 2009-10: Cuarto Rojo del Este, Cuadrante Estelar Sur'),
            ('sincronario','libro','tablas_del_tiempo','02-03-02-04-02','Decimocuarta Tabla, 2010-11: Cuarto Blanco del Norte, Cuadrante Estelar Sur'),
            ('sincronario','libro','tablas_del_tiempo','02-03-02-04-03','Decimoquinta Tabla, 2011-12: Cuarto Azul del Oeste, Cuadrante Estelar Sur'),
            ('sincronario','libro','tablas_del_tiempo','02-03-02-04-04','Decimosexta Tabla, 2012-13: Cuarto Amarillo del Sur, Cuadrante Estelar Sur    '),
          ('sincronario','libro','tablas_del_tiempo','02-03-03','Las Claves de las 64 Runas de UR y los 64 Codones del Libro de la Vida Universal'),
            ('sincronario','libro','tablas_del_tiempo','02-03-03-01','Frontal: El Cubo de la Ley de Dieciséis Años, las Claves'),
            ('sincronario','libro','tablas_del_tiempo','02-03-03-02','Trasera: Coda de los Codones, Las Dos Plantillas Completas de los 64 Codones,'),
            ('sincronario','libro','tablas_del_tiempo','02-03-03-03','Interior: Lectura maestra de los 64 Codones y las 64 Runas UR, Plantilla de la Partitura AC-CA'),
      ('sincronario','libro','tablas_del_tiempo','03','III. Libreto de conducta práctica para todos los magos de la Tierra'),
        ('sincronario','libro','tablas_del_tiempo','03-01','La revelación'),
        ('sincronario','libro','tablas_del_tiempo','03-02','Navegando la Nave del Tiempo Tierra 2013: Cómo Leer y Usar las 20 Tablas de la Ley del Tiempo'),
        ('sincronario','libro','tablas_del_tiempo','03-03','La Ley del Tiempo: T(E) = Arte'),
      ('sincronario','libro','tablas_del_tiempo','04','Las 4 Tablas de la Profecía'),
        ('sincronario','libro','tablas_del_tiempo','04-01','Primera Tabla de la Profecía: El Enigma de la Piedra, de Pacal Votan, Telektonon de Dieciséis Años'),
        ('sincronario','libro','tablas_del_tiempo','04-02','Segunda Tabla de la Profecía: El Tiempo de la Profecía, Los 26 Años de la Convergencia Armónica - Ley del Tiempo T(E) = Arte: Cambio de la Mente del Evento Inevitable'),
        ('sincronario','libro','tablas_del_tiempo','04-03','Tercera Tabla de la Profecía: El Portal del Tiempo, El Cubo de la Ley Interdimensional y la Hoja de Ruta y Guía del Mago de la Tierra para el Cubo de la Ley de Dieciséis Años:'),
          ('sincronario','libro','tablas_del_tiempo','04-03-01','Primera Etapa de la Hoja de Ruta: Tiempo de los Siete Videntes y el Reino de los Nueve Señores del Destino'),
            ('sincronario','libro','tablas_del_tiempo','04-03-01-01','Lectura del Mapa de los Siete Videntes'),
            ('sincronario','libro','tablas_del_tiempo','04-03-01-02','Bolontiku: El Reino de los Nueve Señores del Tiempo y el Destino'),
          ('sincronario','libro','tablas_del_tiempo','04-03-02','Segunda Etapa de la Hoja de Ruta: Plantillas CA y la CA'),
            ('sincronario','libro','tablas_del_tiempo','04-03-02-01','Continuidad Aborigen, Plantilla de los 32 Codones y Runas: Camino de la Conducta'),
            ('sincronario','libro','tablas_del_tiempo','04-03-02-02','Conciencia Cósmica, Plantilla CA, 32 Codones y Runa: Camino de Ejercer el Poder'),
          ('sincronario','libro','tablas_del_tiempo','04-03-03','Tercera Etapa de la Hoja de Ruta: Génesis y Onda Encantada de la Aventura de Trece Años Proporción 3:13'),
            ('sincronario','libro','tablas_del_tiempo','04-03-03-01','Los Tres Años de la Nueva Génesis: 1997-2000 DA'),
            ('sincronario','libro','tablas_del_tiempo','04-03-03-02','Oxlahuntiku, La Onda Encantada de la Aventura de la Segunda Creación, 2000-13 DA'),
          ('sincronario','libro','tablas_del_tiempo','04-03-04','Cuarta Etapa de la Hoja de Ruta: Génesis del Dragón y el Mono, Portal Interdimensional'),
            ('sincronario','libro','tablas_del_tiempo','04-03-04-01','Génesis del Dragón, Onda Encantada-Posiciones del Cubo 1-10'),
            ('sincronario','libro','tablas_del_tiempo','04-03-04-02','Génesis del Mono, Onda Encantada-Posiciones del Cubo 11-16 Secuencia de Camelot'),
          ('sincronario','libro','tablas_del_tiempo','04-03-05','Quinta Etapa de la Hoja de Ruta: Secuencias del Heptágono de la Mente'),
          ('sincronario','libro','tablas_del_tiempo','04-03-06','Sexta Etapa de la Hoja de Ruta: 4x4 Armónicas Maestras del Cubo'),
            ('sincronario','libro','tablas_del_tiempo','04-03-06-01','Los Tres Planos y la Fuente Divina, Cubo Diario'),
            ('sincronario','libro','tablas_del_tiempo','04-03-06-02','Los Cuatro Conjuntos de Años Semilla-Tormenta, Cubo Anual'),
            ('sincronario','libro','tablas_del_tiempo','04-03-06-03','Los Cuatro Castillos del Tiempo, Cubo de la Onda Encantada de 1300 Años'),
            ('sincronario','libro','tablas_del_tiempo','04-03-06-04','Los Cuatro Cuadrantes Estelares'),
          ('sincronario','libro','tablas_del_tiempo','04-03-07','Séptima Etapa de la Hoja de Ruta: El Cubo Detonado por la Quinta Fuerza'),
        ('sincronario','libro','tablas_del_tiempo','04-04','Cuarta Tabla de la Profecía: Tabla de las 64 Runas y Codones, Invocación del Manitú Planetario'),
          ('sincronario','libro','tablas_del_tiempo','04-04-01','Los Ocho Caminos del Sendero de UR de la Vida Universal, el Oráculo del Mago'),
          ('sincronario','libro','tablas_del_tiempo','04-04-02','Invocación del Manitú Planetario'),
      ('sincronario','libro','tablas_del_tiempo','05','LAS 16 Tablas de la Ley del Tiempo de Pacal Votan'),
        ('sincronario','libro','tablas_del_tiempo','05-01','16 años del Cubo de la Ley del Telektonon, Jugando el Cronógrafo, Lectura de la Partitura'),
        ('sincronario','libro','tablas_del_tiempo','05-02','Lado Uno: Cómo Jugar el Cronógrafo de 16 años del Telektonon, Génesis Galáctica de la Nave Tiempo Tierra 2013'),
        ('sincronario','libro','tablas_del_tiempo','05-03','Lado Dos: Cómo leer la Partitura; Tejiendo el Manitú Planetario, Los 7 Días y 13 Tonos de la Creación'),
      ('sincronario','libro','tablas_del_tiempo','06','Las Claves de las 64 Codones y Runas UR del Libro de la Vida Universal'),
        ('sincronario','libro','tablas_del_tiempo','06-01','Introducción: "Y los Ríos se Abrieron para los Justos"'),
        ('sincronario','libro','tablas_del_tiempo','06-02','Portada: Claves de los 64 Codones y Runas UR del Libro de la Vida Universal'),
          ('sincronario','libro','tablas_del_tiempo','06-02-01','Centro: Portal del Tiempo'),
          ('sincronario','libro','tablas_del_tiempo','06-02-02','Tabla Uno: Las 64 Runas, Lenguaje Universal de la Telepatía'),
          ('sincronario','libro','tablas_del_tiempo','06-02-03','Tabla Dos: Los 64 Codones, Lenguaje Universal de la Vida'),
          ('sincronario','libro','tablas_del_tiempo','06-02-04','Tabla Tres: Frecuencia del Tiempo 13:20, Lenguaje Universal del Tiempo'),
          ('sincronario','libro','tablas_del_tiempo','06-02-05','Tabla Cuatro: T(E) = Arte, El Manitú Planetario'),
        ('sincronario','libro','tablas_del_tiempo','06-03','Páginas Interiores: Los 64 Codones del Libro de la Vida Universal: Dos Plantillas'),
          ('sincronario','libro','tablas_del_tiempo','06-03-01','Cuatro Letras Binarias'),
          ('sincronario','libro','tablas_del_tiempo','06-03-02','La Arquitectura de las Tres Letras Binarias del Codón'),
          ('sincronario','libro','tablas_del_tiempo','06-03-03','Las Ocho Tripletas de los Codones'),
          ('sincronario','libro','tablas_del_tiempo','06-03-04','La Arquitectura de las Dos Tripletas del Codón'),
          ('sincronario','libro','tablas_del_tiempo','06-03-05','Índice de los 64 Codones y Runas UR'),
            ('sincronario','libro','tablas_del_tiempo','06-03-05-01','Plantilla AC'),
            ('sincronario','libro','tablas_del_tiempo','06-03-05-02',''),
        ('sincronario','libro','tablas_del_tiempo','06-04','Cubierta Posterior: Coda de los Codones.'),    
          ('sincronario','libro','tablas_del_tiempo','06-04-01','Orden del Cielo Posterior o Secuencial'),
          ('sincronario','libro','tablas_del_tiempo','06-04-02','Orden del Cielo Anterior o Primario'),
          ('sincronario','libro','tablas_del_tiempo','06-04-03','Disposición Primigenia o Anterior del Cielo'),
      ('sincronario','libro','tablas_del_tiempo','07','Anexos'),
        ('sincronario','libro','tablas_del_tiempo','07-01','Epílogo: Viviendo el Misterio'),
        ('sincronario','libro','tablas_del_tiempo','07-02','Índice Maestro: 832 Codones / 832 Semanas – Indicado en las Tablas del Cronógrafo'),
        ('sincronario','libro','tablas_del_tiempo','07-03','Código profético de Valum Votan'),
        ('sincronario','libro','tablas_del_tiempo','07-04','Recuperación del Plan Divino'),
        ('sincronario','libro','tablas_del_tiempo','07-05','Samadhi de Pacal Votan: Recuerdo de la religión universal en la Tierra')
    ;
    -- el átomo del tiempo
    DELETE FROM `sis-app_nav` WHERE `esq` = 'sincronario' AND `cab` = 'libro' AND `art` = 'atomo_del_tiempo'; INSERT INTO `sis-app_nav` VALUES 
      ('sincronario','libro','atomo_del_tiempo','01','Introducción: Modelo del Universo Plasma - Matriz Radial (MR-MUP)'),
        ('sincronario','libro','atomo_del_tiempo','01-01','El modelo de universo plasma'),
        ('sincronario','libro','atomo_del_tiempo','01-02','La matriz radial'),
        ('sincronario','libro','atomo_del_tiempo','01-03','Los 3 niveles'),
      ('sincronario','libro','atomo_del_tiempo','02','La Práctica del 7:7::7:7, Índice e Inventario de Partes'),
        ('sincronario','libro','atomo_del_tiempo','02-01','La práctica'),
        ('sincronario','libro','atomo_del_tiempo','02-02','Cada día'),
        ('sincronario','libro','atomo_del_tiempo','02-03','Cada semana'),
      ('sincronario','libro','atomo_del_tiempo','03','Índice del 7:7::7:7'),
        ('sincronario','libro','atomo_del_tiempo','03-01','Los Siete Plasmas Radiales'),
        ('sincronario','libro','atomo_del_tiempo','03-02','Átomo Telepático del Tiempo'),
        ('sincronario','libro','atomo_del_tiempo','03-03','7 x 4 Juegos Semanales de Color'),
        ('sincronario','libro','atomo_del_tiempo','03-04','Heptágono de la Mente'),
        ('sincronario','libro','atomo_del_tiempo','03-05','Las Cuatro Iniciaciones Semanales'),
        ('sincronario','libro','atomo_del_tiempo','03-06','Las Siete Autodeclaraciones Diarias de Padmasambhava'),
        ('sincronario','libro','atomo_del_tiempo','03-07','Los Siete Chakras y el Cubo del Radión'),
      ('sincronario','libro','atomo_del_tiempo','04','Catálogo de las Partes del 7:7::7:7'),
        ('sincronario','libro','atomo_del_tiempo','04-01','7:7::7:7 Revelación de 28 Días del Tablero del Plasma de Compresión Fractal del Tiempo'),
          ('sincronario','libro','atomo_del_tiempo','04-01-01','Semana 1'),
          ('sincronario','libro','atomo_del_tiempo','04-01-02','Semana 2'),
          ('sincronario','libro','atomo_del_tiempo','04-01-03','Semana 3'),
          ('sincronario','libro','atomo_del_tiempo','04-01-04','Semana 4'),
        ('sincronario','libro','atomo_del_tiempo','04-02','Descripción de las 28 Cartas del Plasma'),
          ('sincronario','libro','atomo_del_tiempo','04-02-01','Frente'),
          ('sincronario','libro','atomo_del_tiempo','04-02-02','Dorso'),
          ('sincronario','libro','atomo_del_tiempo','04-02-03','Resumen'),
        ('sincronario','libro','atomo_del_tiempo','04-03','La Hoja de Instrucciones del 7:7::7:7'),  
          ('sincronario','libro','atomo_del_tiempo','04-03-01','Holograma Cúbico 7:28'),
          ('sincronario','libro','atomo_del_tiempo','04-03-02','Física del Cubo de la Ley'),
          ('sincronario','libro','atomo_del_tiempo','04-03-03','Modelo de Estudio del Tablero del Plasma'),
          ('sincronario','libro','atomo_del_tiempo','04-03-04','Siete Tierras de UR la Escritura Oculta de las Lunas'),
      ('sincronario','libro','atomo_del_tiempo','05','Apéndices'),
        ('sincronario','libro','atomo_del_tiempo','05-01','01) Raíces del 7:7::7:7 en el Telektonon'),
        ('sincronario','libro','atomo_del_tiempo','05-02','02) Fuente de MUP Modelo Universal del Plasma'),
        ('sincronario','libro','atomo_del_tiempo','05-03','03) Triunfo de UR'),
        ('sincronario','libro','atomo_del_tiempo','05-04','04) La Séptima Luna y las Siete Tierras de UR'),
        ('sincronario','libro','atomo_del_tiempo','05-05','05) La Revelación 7:7::7:7'),
        ('sincronario','libro','atomo_del_tiempo','05-06','06) Cierre del Ciclo: Las Siete Últimas Lunas de los Trece Baktunes Heptágono Interior de la Mente'),
        ('sincronario','libro','atomo_del_tiempo','05-07','07) Cierre del Ciclo: Kin del Cronógrafo 201'),
        ('sincronario','libro','atomo_del_tiempo','05-08','08) Cierre del Ciclo: Siete Lunas Místicas para el Lanzamiento de la Nave del Tiempo Tierra 2013'),
        ('sincronario','libro','atomo_del_tiempo','05-09','09) 7:7::7:7, 4:7::7:13, y la constante 13:7'),
        ('sincronario','libro','atomo_del_tiempo','05-10','10) El Libro de las Siete Generaciones y las Profecías de Chilam Balam'),
        ('sincronario','libro','atomo_del_tiempo','05-11','11) Votan Recordado, Parte II: Avatares de la Tradición de Chilam Balam')
    ;
    -- el sincronotron
    DELETE FROM `sis-app_nav` WHERE `esq` = 'sincronario' AND `cab` = 'libro' AND `art` = 'sincronotron'; INSERT INTO `sis-app_nav` VALUES     
      ('sincronario','libro','sincronotron','01','Introducción'),
        ('sincronario','libro','sincronotron','01-01','El sistema del Synchronotron'),
        ('sincronario','libro','sincronotron','01-02','Bases para la Práctica Básica del Synchronotron'),
          ('sincronario','libro','sincronotron','01-02-01','Cómo entrar en la Matriz del Cubo 441'),
          ('sincronario','libro','sincronotron','01-02-02','0. Puerta de la Heptada'),
          ('sincronario','libro','sincronotron','01-02-03','1. Matriz Tiempo'),
          ('sincronario','libro','sincronotron','01-02-04','2. Matriz Espacio '),
          ('sincronario','libro','sincronotron','01-02-05','3. Matriz Sincrónica'),
          ('sincronario','libro','sincronotron','01-02-06','4. Frecuencia Maestra de Coordinación'),
          ('sincronario','libro','sincronotron','01-02-07','5. Frecuencia Armónica Acumulada'),
          ('sincronario','libro','sincronotron','01-02-08','6. Notas de la Escala Diatónica diarias'),
          ('sincronario','libro','sincronotron','01-02-09','7. Perceptor Holomental'),                                    
        ('sincronario','libro','sincronotron','01-03','Videos de Valum Votan explicando el Synchrontron'),    
        ('sincronario','libro','sincronotron','01-04','Código Diário - Ciclo de 63 días'),
      ('sincronario','libro','sincronotron','02','Práctica'),
        ('sincronario','libro','sincronotron','02-01','Cálculos básicos de la Heptada'),
        ('sincronario','libro','sincronotron','02-02','Hunab Ku 21'),
        ('sincronario','libro','sincronotron','02-03','Plantillas del Synchronotron'),
        ('sincronario','libro','sincronotron','02-04','Plantillas Senderos Células'),
      ('sincronario','libro','sincronotron','03','Boletines Intergalácticos'),
        ('sincronario','libro','sincronotron','03-01','Diccionario de los Números 1-441'),
        ('sincronario','libro','sincronotron','03-02','Perceptor Holomental, Qué es y cómo utilizarlo'),
        ('sincronario','libro','sincronotron','03-03','Principios de Memorización Telepática'),
        ('sincronario','libro','sincronotron','03-04','La Ley del Tiempo y el Descenso de la Supermente '),
        ('sincronario','libro','sincronotron','03-05','Synchronotron Un Sendero de Regreso a las Estrellas'),
        ('sincronario','libro','sincronotron','03-06','Synchronotron 441, Historia Cósmica y los Nueve Señores del Tiempo'),
        ('sincronario','libro','sincronotron','03-07','Cómo entrar en Hunab Ku 21'),
        ('sincronario','libro','sincronotron','03-08','Regreso a lo Básico'),
        ('sincronario','libro','sincronotron','03-09','Arquetipos, Lentes del Tiempo y Unidades Telektonon'),
        ('sincronario','libro','sincronotron','03-10','Códigos Clave'),
        ('sincronario','libro','sincronotron','03-11','Visualización, Construcción de la Estructura Arquetípica'),
        ('sincronario','libro','sincronotron','03-12','Synchronotron y Textos Sagrados'),
        ('sincronario','libro','sincronotron','03-13','Actívate con el Perceptor Holomental'),
        ('sincronario','libro','sincronotron','03-14','Matriz de los Sentidos Holográfica'),
        ('sincronario','libro','sincronotron','03-15','Sol, 7 Ángeles Solares y ADN'),
        ('sincronario','libro','sincronotron','03-16','Índice Perceptor Holomental'),
        ('sincronario','libro','sincronotron','03-17','Reto del Synchronotron: Cubica Tu Destino'),
      ('sincronario','libro','sincronotron','04','Material Complementario'),
        ('sincronario','libro','sincronotron','04-01','Cuaderno Mágico del Tiempo'),
        ('sincronario','libro','sincronotron','04-02','Los 7 Postulados del Sistema Operativo Galáctico  '),
        ('sincronario','libro','sincronotron','04-03','Mensaje de Mevlana/Bülent Çorak  '),
        ('sincronario','libro','sincronotron','04-04','19 Puntos sobre Sirio  '),
        ('sincronario','libro','sincronotron','04-05','Por el Comando del Sistema Central Comunicado de la Sección de la Unificación de la Materia  '),
        ('sincronario','libro','sincronotron','04-06','Boletín del Proyecto Rinri III, Edición del Misterio de la Piedra, Volumen 3, Nº 3  '),
        ('sincronario','libro','sincronotron','04-07','APENDICE VOL 6 I-CHING GALACTICO  '),
        ('sincronario','libro','sincronotron','04-08','DICCIONARIO DE LOS NÚMEROS 0-441 EN CURSO  '),
        ('sincronario','libro','sincronotron','04-09','I Ching Perpetuo de 28 Dias  '),
        ('sincronario','libro','sincronotron','04-10','Programa 128 codones noosfera  '),
        ('sincronario','libro','sincronotron','04-11','Las 48 Runas Ur Armónicas de La Segunda Creación y otros elementos del Arbol De La Vida Telepático Parlan')              
    ;
    --
  --
  -- 2- Lecturas
    DELETE FROM `sis-app_nav` WHERE `esq` = 'sincronario' AND `cab` = 'lectura';

    -- Tutorial del Sincronario de 13 lunas
    DELETE FROM `sis-app_nav` WHERE `esq` = 'sincronario' AND `cab` = 'lectura' AND `art` = 'tutorial'; INSERT INTO `sis-app_nav` VALUES 
      ('sincronario','lectura','tutorial','01','Ciclos Simples'),
      ('sincronario','lectura','tutorial','02','Cada día es un Portal Galáctico'),
      ('sincronario','lectura','tutorial','03','Incorporándolo todo'),
        ('sincronario','lectura','tutorial','03-01','Los días de la semana'),
        ('sincronario','lectura','tutorial','03-02','La Fecha en 13 Lunas'),
        ('sincronario','lectura','tutorial','03-03','La fecha gregoriana'),
        ('sincronario','lectura','tutorial','03-04','La Firma Galáctica diaria'),
        ('sincronario','lectura','tutorial','03-05','Las Fases Lunares'),
      ('sincronario','lectura','tutorial','04','El Oráculo de Quinta Fuerza'),
        ('sincronario','lectura','tutorial','04-01','¿Qué es la Quinta Fuerza?'),
        ('sincronario','lectura','tutorial','04-02','El tablero del Oráculo'),
        ('sincronario','lectura','tutorial','04-03','Los Oráculos'),
        ('sincronario','lectura','tutorial','04-04','El Oráculo de Quinta Fuerza y ​​el Tiempo Net '),
      ('sincronario','lectura','tutorial','05','La Firma Galáctica'),
      ('sincronario','lectura','tutorial','06','El Banco-Psi'),
      ('sincronario','lectura','tutorial','07','El Nuevo Ciclo de Sirio: Sistema de Fechación Cronológica')      
    ;    
  --
  -- 3- Códigos

    -- Introduccion
    DELETE FROM `sis-app_nav` WHERE `esq` = 'sincronario' AND `cab` = 'codigo' AND `art` = 'introduccion'; INSERT INTO `sis-app_nav` VALUES

      ('sincronario','codigo','introduccion','01','Sistema de Cuentas')      
    ;
    -- x7 : plasma radial
    DELETE FROM `sis-app_nav` WHERE `esq` = 'sincronario' AND `cab` = 'codigo' AND `art` = 'plasma'; INSERT INTO `sis-app_nav` VALUES

      ('sincronario','codigo','plasma','01','Días del Giro Lunar'),
        ('sincronario','codigo','plasma','01-01','Autodelcaraciones Diarias'),
      ('sincronario','codigo','plasma','02','Sellos de la profecía'),
        ('sincronario','codigo','plasma','02-01','El heptágono de la Mente'),      
      ('sincronario','codigo','plasma','03','Componentes Electrónicos'),
        ('sincronario','codigo','plasma','03-01','Las 12 Líneas Electrónicas de Fuerza'),
        ('sincronario','codigo','plasma','03-02','Los 6 Tipos de Electricidad'),
        ('sincronario','codigo','plasma','03-03','Los 3 Quántums'),
      ('sincronario','codigo','plasma','04','El Holon Humano'),
        ('sincronario','codigo','plasma','04-01','Los 7 Chakras')
    ;
    -- x13 : tono galáctico
    DELETE FROM `sis-app_nav` WHERE `esq` = 'sincronario' AND `cab` = 'codigo' AND `art` = 'tono'; INSERT INTO `sis-app_nav` VALUES
      
      ('sincronario','codigo','tono','01','Los Rayos de Pulsación'),
        ('sincronario','codigo','tono','01-01','Los 7 pares especulares'),
      ('sincronario','codigo','tono','02','Principios de la Creación'),
        ('sincronario','codigo','tono','02-01','Los 4 púlsares dimensionales'),
        ('sincronario','codigo','tono','02-02','Los 5 púlsares matices'),
      ('sincronario','codigo','tono','03','La Onda Encantada de la Aventura'),
        ('sincronario','codigo','tono','03-01','El Castillo del Destino'),
      ('sincronario','codigo','tono','04','El Holon Humano'),
        ('sincronario','codigo','tono','04-01','Las 13 Articulaciones Principales'),
        ('sincronario','codigo','tono','04-02','Los 7 Sentidos de la resonancia Electromagnética')
    ; 
    -- x20 : Sello solar
    DELETE FROM `sis-app_nav` WHERE `esq` = 'sincronario' AND `cab` = 'codigo' AND `art` = 'sello'; INSERT INTO `sis-app_nav` VALUES

      ('sincronario','codigo','sello','01','El código de la Luz y de la Vida'),
      ('sincronario','codigo','sello','02','Rangos de Frecuencia para Símbolos ideográficos'),
        ('sincronario','codigo','sello','02-01','La Matriz Direccional'),
        ('sincronario','codigo','sello','02-02','Las 3 etapas en el Desarrollo del Ser'),
        ('sincronario','codigo','sello','02-03','Las 5 Familias Cíclicas de la Luz'),
      ('sincronario','codigo','sello','03','Los Códigos del Encantamiento del Sueño'),
        ('sincronario','codigo','sello','03-01','El Código Encantado'),
        ('sincronario','codigo','sello','03-02','El Código 0-19'),
      ('sincronario','codigo','sello','04','Colocación Cromática'),
        ('sincronario','codigo','sello','04-01','Los 4 Clanes Galácticos'),
        ('sincronario','codigo','sello','04-02','Las 5 Familias Terrestres'),        
      ('sincronario','codigo','sello','05','Colocación Armónica'),
        ('sincronario','codigo','sello','05-01','Las 4 Razas Raíz Cósmicas'),        
        ('sincronario','codigo','sello','05-02','Las 5 Células del Tiempo'),
      ('sincronario','codigo','sello','06','El Holon Solar'),
        ('sincronario','codigo','sello','06-01','Los 2 Flujos Polares'),
        ('sincronario','codigo','sello','06-02','Las 10 Órbitas planetarias'),
        ('sincronario','codigo','sello','06-03','Las 5 Células Solares'),
        ('sincronario','codigo','sello','06-04','Los 5 Circuitos de telepatía'),
      ('sincronario','codigo','sello','07','El Holon Planetario'),
        ('sincronario','codigo','sello','07-01','Los 2 Flujos Polares'),
        ('sincronario','codigo','sello','07-02','Los 5 Centros de la Fuerza-G'),
      ('sincronario','codigo','sello','08','El Holon Humano'),
        ('sincronario','codigo','sello','08-01','Los 2 Lados de la Respiración S-G'),
        ('sincronario','codigo','sello','08-02','Los 5 Centros Galácticos'),
        ('sincronario','codigo','sello','08-03','Las 4 Extremidades Cromáticas'),
        ('sincronario','codigo','sello','08-04','Las 5 Dedos de las manos y los pies'),
        ('sincronario','codigo','sello','08-05','Los 10 Meridianos')
    ;
    -- x28 : Giro Lunar
    DELETE FROM `sis-app_nav` WHERE `esq` = 'sincronario' AND `cab` = 'codigo' AND `art` = 'luna'; INSERT INTO `sis-app_nav` VALUES

      ('sincronario','codigo','luna','00','Introducción')
    ;   
    -- x260 : kines
    DELETE FROM `sis-app_nav` WHERE `esq` = 'sincronario' AND `cab` = 'codigo' AND `art` = 'kin'; INSERT INTO `sis-app_nav` VALUES

      ('sincronario','codigo','kin','00','Introducción'),
      ('sincronario','codigo','kin','01','El Calendario Sagrado Maya: Tzolkin'),
        ('sincronario','codigo','kin','01-01','Los 20 Sellos Solares'),
        ('sincronario','codigo','kin','01-02','Los 13 Tonos Galácticos'),        
      ('sincronario','codigo','kin','02','El Módulo Armónico'),
        ('sincronario','codigo','kin','02-01','Los 52 portales de Activación Galáctica'),
        ('sincronario','codigo','kin','02-02','Los 64 Hexagramas del I-Ching'),        
        ('sincronario','codigo','kin','02-03','Los 13 Campos de Energía'),      
      ('sincronario','codigo','kin','03','El Giro Espectral'),        
        ('sincronario','codigo','kin','03-01','Las 4 Estaciones Galácticas'),
        ('sincronario','codigo','kin','03-02','Los 52 Elementos Cromáticos'),
      ('sincronario','codigo','kin','04','El Giro Galáctico'),
        ('sincronario','codigo','kin','04-01','Las 13 Trayectorias Armónicas'),
        ('sincronario','codigo','kin','04-02','Las 65 Células del Tiempo'),
      ('sincronario','codigo','kin','05','La Nave del Tiempo'),
        ('sincronario','codigo','kin','05-01','Los 5 Castillos Direccionales'),
        ('sincronario','codigo','kin','05-02','Las 20 Ondas Encantadas de la Aventura'),
      ('sincronario','codigo','kin','06','El Oráculo del Destino'),
        ('sincronario','codigo','kin','06-01','Los Patrones del Destino'),
        ('sincronario','codigo','kin','06-02','Las Relaciones de Color'),
          ('sincronario','codigo','kin','06-02-01','Las 10 Parejas Análogas'),
          ('sincronario','codigo','kin','06-02-02','Las 10 Parejas Antípodas'),
          ('sincronario','codigo','kin','06-02-03','Las 10 Parejas Ocultas'),
          ('sincronario','codigo','kin','06-02-04','Los Patrones de la Pareja Guía'),        
        ('sincronario','codigo','kin','06-03','La Sincronometría del Oráculo'),
        ('sincronario','codigo','kin','06-04','El Tiempo N.E.T.')
    ;
    -- x365 : psi-cronos 
    DELETE FROM `sis-app_nav` WHERE `esq` = 'sincronario' AND `cab` = 'codigo' AND `art` = 'psi'; INSERT INTO `sis-app_nav` VALUES
      ('sincronario','codigo','psi','00','Introducción'),
      ('sincronario','codigo','psi','01','El Anillo Solar'),
        ('sincronario','codigo','psi','01-01','Las 13 Lunas del Servicio Planetario'),
        ('sincronario','codigo','psi','01-02','Las 4 Estaciones Solares del Castillo'),
        ('sincronario','codigo','psi','01-03','Las 52 Héptadas Anuales'),
      ('sincronario','codigo','psi','02','El Banco-Psi'),
        ('sincronario','codigo','psi','02-01','La Matriz Base'),
        ('sincronario','codigo','psi','02-02','Los Cinturones de Radiación'),
        ('sincronario','codigo','psi','02-03','Como Bancos de Memoria'),
      ('sincronario','codigo','psi','03','Códigos y Cuentas del Tzolkin'),
        ('sincronario','codigo','psi','03-01','El Psi-crono'),
        ('sincronario','codigo','psi','03-02','Las 73 Cromáticas Entonadas'),
        ('sincronario','codigo','psi','03-03','Los 19 Vinales del Haab'),
        ('sincronario','codigo','psi','03-04','Los 52 años de Nuevo Sirio')
    ;  
  --
--