
-- letra
  DELETE FROM `sis-tex_let`;
  INSERT INTO `sis-tex_let` (`pos`,`ide`,`tip`,`var`) VALUES
    ( NULL, '.', 'ope', 'cod' ),
    ( NULL, ',', 'ope', 'cod' ),
    ( NULL, ':', 'ope', 'cod' ),
    ( NULL, ';', 'ope', 'cod' ),
    ( NULL, '\\','ope', 'cod' ),
    ( NULL, '~', 'ope', 'val' ),
    ( NULL, '°', 'ope', 'val' ),
    ( NULL, 'º', 'ope', 'val' ),
    ( NULL, '#', 'ope', 'val' ),
    ( NULL, '$', 'ope', 'val' ),
    ( NULL, '@', 'ope', 'val' ),          
    ( NULL, '=', 'ope', 'num' ),  
    ( NULL, '+', 'ope', 'num' ),
    ( NULL, '-', 'ope', 'num' ),    
    ( NULL, '*', 'ope', 'num' ),
    ( NULL, '/', 'ope', 'num' ),
    ( NULL, '%', 'ope', 'num' ),
    ( NULL, '<', 'ope', 'num' ),
    ( NULL, '>', 'ope', 'num' ),
    ( NULL, '–', 'ope', 'tex' ),
    ( NULL, "'", 'ope', 'tex' ),  
    ( NULL, '’', 'ope', 'tex' ),  
    ( NULL, '`', 'ope', 'tex' ),  
    ( NULL, '"', 'ope', 'tex' ),
    ( NULL, '“', 'ope', 'tex' ),
    ( NULL, '”', 'ope', 'tex' ),    
    ( NULL, '¡', 'ope', 'tex' ),
    ( NULL, '!', 'ope', 'tex' ),
    ( NULL, '¿', 'ope', 'tex' ),
    ( NULL, '?', 'ope', 'tex' ),  
    ( NULL, '(', 'ope', 'lis' ),
    ( NULL, ')', 'ope', 'lis' ),
    ( NULL, '[', 'ope', 'pos' ),
    ( NULL, ']', 'ope', 'pos' ),
    ( NULL, '{', 'ope', 'atr' ),
    ( NULL, '}', 'ope', 'atr' )
  ;