-- fecha
DROP TABLE IF EXISTS `var-fec_dat`;
CREATE TABLE `var-fec_dat` ( 
  `año` SMALLINT(4) UNSIGNED ZEROFILL NULL DEFAULT NULL COMMENT 'Año',
  `mes` TINYINT(2) UNSIGNED ZEROFILL NULL DEFAULT NULL COMMENT 'Mes',
  `dia` TINYINT(2) UNSIGNED ZEROFILL NULL DEFAULT NULL COMMENT 'Dia',
  `sem` TINYINT(1) UNSIGNED ZEROFILL NULL DEFAULT NULL COMMENT 'Semana',
  `hor` TINYINT(2) UNSIGNED ZEROFILL NULL DEFAULT NULL COMMENT 'Hora',
  `min` TINYINT(2) UNSIGNED ZEROFILL NULL DEFAULT NULL COMMENT 'Minuto',
  `seg` TINYINT(2) UNSIGNED ZEROFILL NULL DEFAULT NULL COMMENT 'Segundo',
  `kin` SMALLINT(3) UNSIGNED ZEROFILL NULL DEFAULT NULL COMMENT 'Kin',
  `psi` SMALLINT(3) UNSIGNED ZEROFILL NULL DEFAULT NULL COMMENT 'Psi',
  `ani` TINYINT(2) UNSIGNED ZEROFILL NULL DEFAULT NULL COMMENT 'Anillo',
  `sir` SMALLINT(2) NULL DEFAULT NULL COMMENT 'Nuevo Sirio' 
) ENGINE = InnoDB COMMENT = 'Fecha'
;

DELETE FROM `var-fec_dat`
;