DELETE FROM `hol_rad`; INSERT INTO `hol_rad` VALUES
(1, 'Dali', 'amarillo', 'Apunta', '01, 08, 15, 22', 
  'Profecía del Año Uno', '\"La Victoria Da en el Blanco\"', 1993, 144, 248, 194, 
  '\"Dalí liberada, capacidad técnica lumínica establecida\"', 
  '\"Focaliza la Fuerza Térmica\"', 'Focaliza', 'Fuerza Térmica', 01, 02, 1, 'Om', 1, 'Arriba', 
  '\"Mi Padre es la Consciencia Intrínseca. Yo Siento el Calor.\"', 
  1, 
  108, 'Fuente Omnigaláctica', 'Cristo', 'Trono', 'Alfa-Alfa', 'Preconsciente (Hemisferio Derecho Trasero)', 'Samadhi Profundo'
),
(2, 'Seli', 'rojo', 'Fluye', '02, 09, 16, 23', 
  'Profecía del Año Dos', '\"La Victoria Fluye\"', 1994, 249, 093, 195, 
  '\"Seli liberada, capacidad térmica-lumínica ampliada\"', 
  '\"Fluye Fuerza Lumínica\"', 'Fluye', 'Fuerza Lumínica', 03, 03, 1, 'Hram', 2, 'Abajo', 
  '\"Mi Madre es la Esfera última. Yo Veo la Luz.\"', 
  7, 
  291, 'Tierra Cristal', 'Mahoma', 'Avatar', 'Alfa-Beta', 'Subconsciente (Hemisferio Derecho Frontal)', 'Samadhi Informativo'
),
(3, 'Gama', 'blanco', 'Pacifica', '03, 10, 17, 24', 
  'Profecía del Año Tres', '\"La Victoria Pacifica\"', 1995, 094, 198, 196, 
  '\"Gamma liberada capacidad térmica-lumínica ampliada, alcanza el poder extraordinario\"', 
  '\"Fuerza de Impacto Lumínico-Térmica\"', 'Pacifica', 'Fuerza Pacificadora', 04, 05, 1, 'Hraha', 3, 'Derecha', 
  '\"Mi Linaje es la Unión de la Consciencia Intrínseca y la Esfera Última.\"', 
  2, 
  144, 'Hubab Ku', 'Pacal Votan', 'Misterio', 'Beta-Beta', 'Consciente (Hemisferio Izquierdo Frontal)', 'Mediumnidad del Consciente Des'
),
(4, 'Kali', 'azul', 'Establece', '04, 11, 18, 25', 
  'Profecía del Año Cuatro', '\"La Victoria Establece\"', 1996, 199, 043, 197, 
  '\"Kali liberada, capacidad Normativa de cohesión-distensión catalítica alcanzada\"', 
  '\"Establece la Cohesión-Distensión\"', 'Establece', 'Agente Catalizador', 06, 06, 2, 'Hrim', 4, 'Izquierda', 
  '\"Mi Nombre es el Glorioso Nacido del Loto. Yo Catalizo la Luz-Calor Adentro.\"', 
  6, 
  515, 'Ahau Kin', 'Quetzalcoatl', 'Iniciación', 'Beta-Alta', 'Consciente Contínuo (Hemisferio Izquierdo Trasero)', 'Control de la Mente Superior'
),
(5, 'Alfa', 'amarillo', 'Libera', '05, 12, 19, 26', 
  'Profecía del Año Cinco', '\"La Victoria Libera\"', 1997, 044, 148, 198, 
  '\"Alfa liberado, activación del doble electrón extendido, Cubo de la Ley plásmicamente liberado como experiencia de la Telepatía Universal\"', 
  '\"Libera el Electrón Doble-Extendido\"', 'Libera', 'Electrón Doble-Extendido', 07, 07, 3, 'Hraum', 5, 'Frente', 
  '\"Mi país es la esfera última no-nacida. Yo libero el Electrón Doble- Extendido en el Polo Sur.\"', 
  3, 
  414, 'Sirio', 'San Juan', 'Tiempo-Espacio', 'Hiper Electrón', 'Superconsciente (Conecta Lobulo Frontal y Trasero Derecho)', 'Superconsciente HiperElectróni'
),
(6, 'Limi', 'rojo', 'Purifica', '06, 13, 20, 27', 
  'Profecía del Año Seis', '\"La Victoria Purifica\"', 1998, 149, 253, 199, 
  '\"Limi liberada generando el electrón mental, la mente galáctica fortalece la mente Telepática de la Tierra con los poderes generativos del electrón\"', 
  '\"Purifica el Electrón Mental\"', 'Purifica', 'Electrón Metal', 09, 09, 3, 'Hrum', 6, 'Detrás', 
  '\"Yo consumo pensamientos dualistas como si fueran alimento. Yo purifico el Electrón Mental en el Polo Norte.\"', 
  5, 
  402, 'Estación Intermedia AA', 'Padmasambhava', 'Trascendencia', 'Hiper Neutrón', 'Consciente Subliminal (Conecta Lobulo Frontal y Trasero Izquierdo)', 'Consciente Subliminal HiperNeu'
),
(7, 'Silio', 'blanco', 'Descarga', '07, 14, 21, 28', 
  'Profecía del Año Siete', '\"La Victoria Descarga\"', 1999, 254, 098, 200, 
  '\"Silio liberado, electrón-neutrón generado, completa la creación del Heptágono de la Mente dispara el Puente Arco iris Circumpolar\"', 
  '\"Descarga el Electrón-Neutrón Mental\"', 'Descarga', 'Electrón-Neutrón Mental', 10, 11, 3, 'Hraim', 7, 'Centro', 
  '\"Mi rol es cumplir las acciones del Buda. Yo descargo el Electrón- Neutrón Mental en el Centro de la Tierra\"', 
  4, 
  441, 'Pléyades', 'Buda', 'Cubo', 'Sirio Beta 52-Elemen', 'Perceptor Holomental (Conecta Todas las Dimensiones del Tiempo)', 'Iluminación Hiperplásmica'
);