-- Glosarios 
  -- del factor maya 
  DELETE FROM `_api`.`doc_ide` WHERE `esq`='hol' AND `ide`='fac';
  INSERT INTO `_api`.`doc_ide` VALUES 
    ('hol','fac','HUNAB KU','El que da el movimiento y medida. El principio de la energía inteligente que llena al universo entero, ya sea animado o  inanimado.'),
    ('hol','fac','HUYUB CAAN','El Corazón de los Cielos. El arquitecto celestial, principio del designio cósmico.'),
    ('hol','fac','KIN','El sol. El principal mediador de Hunab Ku para nuestro sistema  planetario. Día. Unidad armónica fundamental, o propiedad de las  ondas.'),
    ('hol','fac','KINAN','Energía solar. Altísima energía espiritual. La mente  solar  como  medio universal disponible para la transmisión de energía psíquica superior en este planeta.'),
    ('hol','fac','TIN KINANTAH','Cualidad de la energía que transmite el espíritu, energía superior relacionada con el Sol, que da cuenta de las diferentes clases de fenómenos psíquicos o paranormales.'),
    ('hol','fac','KINICH AHAU','El señor del Sol. Supervisor galáctico, la mente solar realizada, o mente de luz.'),
    ('hol','fac','AHAU KINES','Los Señores Solares. Los Sacerdotes del Sol. Los adivinos de la armonía,  videntes.'),
    ('hol','fac','BAAXTEN','El poder de proyectar energía, como también el efecto que  produce dicha proyección de energía.'),
    ('hol','fac','PAX','Ruptura o abertura cósmica, el poder de la  música'),
    ('hol','fac','PIXAN','Lo que se manifiesta dentro de la forma, el  “espíritu”.'),
    ('hol','fac','TIN UILA LUUN TUL PIXAN','Ver una alma o un espíritu. Percibir lo manifestado.'),
    ('hol','fac','KUXAN SUUM','Camino hacia el cielo, que conduce al cordón umbilical del universo. Los hilos invisibles de la sangre vital galáctica, mediados por Kin, el  Sol.'),
    ('hol','fac','CAAN','Los Cielos.'),
    ('hol','fac','CAN','Serpiente, energía, el número cuatro. Cuádruples funciones de la onda energética. Fuerza gravitatoria, fuerza electromagnética, fuerza potente,  y  fuerza  débil (estas dos últimas fuerzas al combinarse, dan origen al campo bio-psíquico o  psi). (En el I Ching, las cuatro funciones de la onda energética corresponden respectivamente a Joven Yin, Joven Yang, Viejo Yang, y Viejo  Yin).'),
    ('hol','fac','NAC','Reverso de Can: Limite, principio de la  forma.'),
    ('hol','fac','CANNAC','La razón por la cual no puede existir ninguna forma sin espíritu, y vice-versa. Complementariedad de la energía y la forma. También, aquello que tiene que ser aprendido.'),
    ('hol','fac','TUMEN','Causa y efecto. El principio de la relación  causal'),
    ('hol','fac','CUXTAL','Llegar a la oxidación (CAXUM). Principio generador de la  vida.'),
    ('hol','fac','CANIL CUXTAL','Serpiente de la vida. Energía que llega a la oxidación, o  que toma forma, limitación de la energía; y por tanto el sufrimiento como cualidad primaria de la existencia.'),
    ('hol','fac','WINCLIL','El ser humano. WINC = tubérculo, raíz, LIL= vibratorio,  y por esta razón humana. Raíz o resonador vibratorio del  cosmos.'),
    ('hol','fac','CI’ZIN','Radicación, rayo, psiquis. La proyección de energía particular, personalidad.'),
    ('hol','fac','ET P’IZ','Nuestra medida. Ley de Karma,  compensación.'),
    ('hol','fac','K’OCHIL','Aquello con lo que hemos nacido, aquello con lo que morimos. Los residuos kármicos que modifican la existencia  individual.'),
    ('hol','fac','YACUNAH','Amor, y al mismo tiempo sufrimiento. El inevitable rigor de la existencia.'),
    ('hol','fac','IN LAKE’CH','Yo soy otro tú. El fundamento del amor universal, compasión.'),
    ('hol','fac','CHAN','La cualidad de la inteligencia. Intelecto.'),
    ('hol','fac','CHICCHAN','Reptil. Mente instintiva. Inteligencia elemental.'),
    ('hol','fac','CHANES','Los primeros hijos del Sol. Mensajeros galácticos.'),
    ('hol','fac','ITZAES','Los primeros hijos del agua. Los atlantes.'),
    ('hol','fac','HOB, HOOL','Cabeza, idea. Mente o facultad  mental.'),
    ('hol','fac','NENHOOL','Espejo de la mente. Toda cosa es la reflexión de uno mismo. El principio del NAGUAL, o doble espiritual del cuerpo de  luz.'),
    ('hol','fac','PANCHE BE','Buscar la raíz de la verdad. El sendero natural de la  existencia.'),
    ('hol','fac','MEN','Creer, crear, hacer. Fuerza mental superior, que representa a PIXAN, es decir, la energía del espíritu, que es intermediada por KINAN, o sea la mente solar superior.'),
    ('hol','fac','H’MENES','Hechiceros, magos, curanderos. Aquellos versados en  MEN.'),
    ('hol','fac','H’ PULYAHES','Los lanceros del mal. Los que abusan de la  energía.'),
    ('hol','fac','DZAC','Medicina, veneno.'),
    ('hol','fac','OL, OLAL','Aquello que es animado o tiene vida. Voluntad, cualidad del espíritu (PIXAN) en cuanto formas de expresión  animadas.'),
    ('hol','fac','OL UOLAH','El espíritu de la voluntad ejercitado de acuerdo a la ley de causa (TUMEN) y efecto (ET P’IZ).'),
    ('hol','fac','LUK’AN TUMEN CAN','Los que llevan la serpiente; los iniciados.'),
    ('hol','fac','TUCU’T','Pensar, venerar.'),
    ('hol','fac','THAN','Gota de agua. Poder de la palabra.'),
    ('hol','fac','HEL, GEL','El huevo, el cero, la base de la  transformación.'),
    ('hol','fac','CANHEL','Serpiente que se transforma a sí misma. Dragón. La totalidad de la cuádruple energía manifestada como un ser energético que se transforma a sí  mismo.'),
    ('hol','fac','CHE, TE','Arbol. TE-OTL.  Espíritu del árbol. Energía divina.'),
    ('hol','fac','YAX','Verde. Poder de renovación.'),
    ('hol','fac','YAXKIN','El centro. Fuente sin fuente. Lugar de  renovación.'),
    ('hol','fac','YAXCHE','El árbol original; El eje del universo. La columna mística. El ser humano como canal.'),
    ('hol','fac','BAAL CHE','Cosa del árbol, ejemplo, animal, poder  animal.'),
    ('hol','fac','TOK’ZAH','Acupuntura.'),
    ('hol','fac','HUP KIIX','Punzar con agujas.'),
    ('hol','fac','XICH','Nervio. Red eléctrica.'),
    ('hol','fac','ZUVUYA','Circuito por el cual todas las cosas regresan hacia sí mismas. El decimotercer cielo, o cielo más alto. Punto planetario de entrada. El lenguaje de los KATUNES, la gramática de la  armonía.'),
    ('hol','fac','TZOLKIN','La cuenta de los días. El Calendario Sagrado, matriz cósmica. El módulo armónico universal que ajusta toda posible permutación de HUNAB KU, que es el dador del movimiento y la medida.')
  ;
  -- del El encantamiento del sueño 
  DELETE FROM `_api`.`doc_ide` WHERE `esq`='hol' AND `ide`='enc';
  INSERT INTO `_api`.`doc_ide` VALUES 
    ('hol','enc','Alfa','En el código Solar-Galáctico 0-19, Plutón y Mercurio tienen el comienzo alfa y el final omega de la inspiración galáctica y expiración solar del aliento de Kinich Ahau.'),
    ('hol','enc','Omega','En el código Solar-Galáctico 0-19, Plutón y Mercurio tienen el comienzo alfa y el final omega de la inspiración galáctica y expiración solar del aliento de Kinich Ahau.'),  
    ('hol','enc','Año solar-galáctico','Ciclo de sincronización de 13 Lunas que va del 26 de julio del calendario gregoriano al 25 de julio del año siguiente.'),
    ('hol','enc','Armónica','El código de la célula del tiempo cooperando con las cuatro razas cósmicas raíz; cinco células del tiempo codificadas con cada uno de los trece tonos galácticos crean las 65 armónicas del Libro del Kin; en relación inversa a cada una de ellas, las 65 armónicas crean el código del Índice Armónico, las parejas ocultas y los cuartetos.'),
    ('hol','enc','Átomo del tiempo cromático','Estructura direccional de las cuatro constantes galácticas de color alrededor una quinta verde central; base de las cinco células del tiempo y los cinco castillos; estructurado como el Cubo de Color, base de todas las relaciones análogas, antípodas y ocultas del Génesis del Oráculo.'),
    ('hol','enc','Aventura','Cualquier acción emprendida por el Kin planetario para la Nave del Tiempo Tierra, formalizada y contada en la corte del Kin, idealmente en el tono cristal de cualquier Onda Encantada.'),
    ('hol','enc','Brújula Galáctica','Herramienta para convertir cualquier fecha tri-dimensional en el umbral cuatri-dimensional; un Efemérides Galáctico, un disco verde de fechas correlacionadas y cinco discos que se mueven.'),
    ('hol','enc','Calendario de 13 Lunas','Ciclo perpetuo de cuatro semanas y 28 días llamado una Luna; trece Lunas para un año solar, menos un día verde (25 de Julio); expresión completa de un módulo de sincronización de trece unidades para estabilizar las 13 lunaciones del planeta Tierra.'),
    ('hol','enc','Cambio de Polos 2000','Punto de inversión desde el tiempo tri-dimensional que va en el sentido del reloj al tiempo cuatri-dimensional que va en contra del sentido del reloj; agotamiento de todos los procesos históricos y materialistas comienzo de la prueba de conducción de la Nave del Tiempo Tierra 2013, abriendo los túneles del tiempo Tierra-Urano.'),
    ('hol','enc','Castillo','Estructura del tiempo cuatri-dimensional, cuatro Ondas Encantadas de 52 Kin: base estructural de la Nave Tiempo Tierra 2013.'),
    ('hol','enc','Castillo del Destino','Cuatro Ondas Encantadas codificadas por el color, la estructura del tiempo galáctico de 52 Kin, la base para trazar varias equivalencias del Kin, incluyendo el sendero del destino de la vida de 52 años, el año de 52 semanas, etc...'),
    ('hol','enc','Célula de memoria del génesis','Una de las cinco series de dos pares antípodas; en el Oráculo, base de la reconstrucción de los 26.000 años del Encantamiento del Sueño de la Nave del Tiempo Tierra 2013.'),
    ('hol','enc','Célula del tiempo','Una de las cinco unidades creadas por el poder de la quinta fuerza codificando las cuatro razas cósmicas raíz; base de auto-circulación de la Nave del Tiempo; combinada con los trece tonos galácticos crea la base de las 65 armónicas del Índice Armónico y el Libro del Kin.'),
    ('hol','enc','Célula solar','Una de las cinco series que consisten en dos pares de parejas  planetarias; las cinco células solares juntas regulan la inhalación galáctica y la exhalación solar autocirculantes del tiempo galáctico; interrumpida durante “las Guerras del tiempo”, la reparación de la célula de transbordo intermedio es esencial para poder entonar el quinto acorde galáctico de Kinich Ahau en el 2013 d.C.'),
    ('hol','enc','Clan','Equipo de colonización galáctica primordial basado en uno de los cuatro elementos galácticos y correspondiendo a uno de los cuatro cromáticos; clan del fuego amarillo, clan de la sangre roja, clan de la verdad blanca, clan del cielo azul.'),
    ('hol','enc','Código punto-raya','Base del sistema de anotación galáctica donde las unidades de 1 a 4 son representadas por un número correspondiente de puntos y cinco (o los múltiplos de cinco) por una raya; 1-5 = código cromático, 1-13 = trece tonos galácticos de la Onda Encantada; 0-19 = sistema de anotación completa de 20 números de la matriz radial; 1-20 = números código de los 20 sellos solares, en donde el cero es igual a 20 o a 0.'),
    ('hol','enc','Código solar-galáctico 0-19','Circulación de información galáctica desde y hacia el Sol a través de diez órbitas planetarias; cada órbita planetaria lleva un número codificado de inhalación (galáctica) y exhalación solar asociado con dos de los 20 sellos solares; la suma de los números codificados emparejados es siempre diecinueve; los pares forman Kin análogos.'),
    ('hol','enc','Código del Encantamiento','Descripción en tres palabras del sello solar encontrado al dorso de las fichas de los sellos solares.'),
    ('hol','enc','Corte del Kin','Cualquier reunión del Kin planetario convocada con el propósito de determinar y escuchar relatos de las aventuras; tiene lugar en el duodécimo Kin (cristal) de cualquier Onda Encantada.'),
    ('hol','enc','Convergencia Armónica','El 16 y 17 de Agosto de 1987, umbral galáctico 3 Águila y 4 Guerrero, marcando el punto en donde comienza la inversión del Encantamiento del Sueño de la Historia; inicio de los 26 años de cuenta atrás de la Nave del Tiempo Tierra.'),
    ('hol','enc','Crédito de tiempo','Reserva de provisión almacenada de relaciones cuatri- dimensionales traducida en bases tridimensionales de crédito personal del Kin; a ser determinado creativa y equitativamente por el Kin planetario en la corte del Kin.'),
    ('hol','enc','Cromático','Cualidad del tiempo cuatri-dimensional como un Génesis que vuelve a circular continuamente; la secuencia de cinco Kin donde el primero y el quinto kin son del mismo color; dinamismo de las cuatro constantes de los colores que evocan y son movidos por el quinto matiz.'),
    ('hol','enc','Cuarto oculto','En el Índice Armónico cualquier par igualado de Kin ocultos, la suma de cuyos tonos galácticos es siempre 28; base del “telar de las trece Luna”, 52 portales de activación galácticos; base del sistema de crédito del Kin.'),
    ('hol','enc','Elemento galáctico','El fuego amarillo, la sangre roja, la verdad blanca, y el celo azul,- la base de las cuatro estaciones galácticas y las cuatro cromáticas.'),
    ('hol','enc','Cuatro razas cósmicas raíz','Rojo, blanco, azul y amarillo son las familias de color formadas por las 20 tribus solares de la Nave del Tiempo Tierra 2013 con el propósito de unirse como la Nación del Arco Iris después del Giro del Tiempo.'),
    ('hol','enc','Cubo de color','Estructura geométrica de seis lados que demuestra las seis relaciones base de colores; caja para guardar las 20 fichas de los sellos solares.'),
    ('hol','enc','Descifrador del código del Encantamiento del Sueño','jugador del Encantamiento del Sueño con habilidad para leer el oráculo y seguir la huella diaria.'),
    ('hol','enc','Día verde','Siempre corresponde a la fecha 25 de julio del calendario Gregoriano, para que el año solar-galáctico sincronice con el ciclo de 52 años; independientemente de las 13 Lunas, el día verde es conocido como el día de la libertad galáctica.'),
    ('hol','enc','Era de Transformación','Los últimos 260 años de los 26.000 años del Encantamiento del Sueño universal, de 1754 al 2013 d.C., basse del Efemérides Galáctico que se encuentra al dorso de la Brújula Galáctica.'),
    ('hol','enc','Efemérides galácticas','los 52 umbrales galácticos para el 26 de julio (situado en el lado blanco de la Brújula Galáctica) que correlaciona el año solar de acuerdo con el ciclo galáctico de 52 años. Cinco series de estos ciclos galácticos de 52 años crean la Era de Transformación desde 1734 a.C. hasta el 2013 d. C.'),
    ('hol','enc','Ego','El equivalente tri-dimensional holón cuatri-dimensional; activa y anima el traje espacial tri-dimensional; también conocido como la personalidad.'),
    ('hol','enc','Encantamiento del Sueño','Función de la regulación planetaria solar-galáctica quinto-dimensional; 26.000 años de ciclos renovables del Génesis de castillos; cualquier realidad en consenso; pasando por alto la realidad interdimensional crea el encantamiento entrópico de la historia; cura para la pérdida de memoria galáctica.'),
    ('hol','enc','Encantamiento del Sueño de la Historia','Proporción 12:60 superpuesta creando exclusivamente el mundo tri-dimensional o la distorsión del tiempo; coincidente con el génesis de la Luna  de  los  5.200  años  del  castillo  del  encantar, -3187 años del Encantamiento del Sueño.'),
    ('hol','enc','Equivalencia del Kin','Diferentes valores acordados al Kin como unidad de medida; equivalencia de proporción.'),
    ('hol','enc','Equivalencia de proporción','Diferentes valores otorgados al Kin; también conocido como la equivalencia del Kin.'),
    ('hol','enc','Estación galáctica','Espectro de 65 Kin, un cuarto de giro espectral codificado por los cuatro Kin polares: Serpiente roja, Perro blanco, Águila azul y sol amarillo.'),
    ('hol','enc','Escudo galáctico','Emblema de la quinta fuerza galáctica que expresa el principio de diseño del despliegue cromático.'),
    ('hol','enc','Familias Terrestres','Una de las cinco series de sellos de cuatro colores codificados; combinados con los trece tonos galácticos, codifican los cumpleaños solares de acuerdo con los 52 años del Castillo del Destino; código horizontal del Holón del Planeta.'),
    ('hol','enc','Ficha del sello solar','Uno de los 20 cuadrados impresos en ambos lados con información sobre las 20 tribus solares para utilizar en la colocación del Tablero del Oráculo, lecturas del Oráculo del Destino y las Ondas Encantadas; en el anverso está impreso el icono solar, al dorso el número del código y el código del encantamiento.'),
    ('hol','enc','Firma galáctica','Nombre adoptado como Kin planetario tomado del título del umbral galáctico correspondiente a la fecha de nacimiento como está registrado en el Libro del Kin.'),
    ('hol','enc','Génesis','Cualquier punto de origen, un nuevo comienzo: en el Encantamiento del Sueño, el Génesis ocurre en tres puntos diferentes: el Dragón magnético, el Mono magnético, y la Luna magnética, recapitulando la proporción de involución 53:3:2.'),
    ('hol','enc','Giro espectral','Castillo del tiempo de 52 cromáticas en donde cada Onda encantada es una estación galáctica de 65 Kin (trece cromáticas); las estaciones están codificadas por el color de la familia Terrestre Polar: estación de la Serpiente roja del Este, estación del Perro blanco del Norte, estación del Águila azul del Oeste y la estación del Sol amarillo del Sur; el propósito de los giros espectrales es entrelazar los giros galácticos con armónicas superiores de la quinta fuerza.'),
    ('hol','enc','Giro del Tiempo','el 26 de Julio de 1992, umbral galáctico 13 Tormenta; punto de implementación del Calendario de 13 Lunas y el despertar de la Nación del Arco Iris para el bien de la Nave del Tiempo Tierra 2013.'),
    ('hol','enc','Holón','Estructura del universo cuatri-dimensional; el cuerpo cuatri-dimensional de cualquier forma en evolución; equivalente cuatri- dimensional del ego Humano tri-dimensional, llamado holón Humano.'),
    ('hol','enc','Holón Humano','La quinta fuerza, la codificación de las 20 tribus solares que conecta el cuerpo cuatri-dimensional con el traje espacial tri-dimensional.'),
    ('hol','enc','Holón del Planeta','La Tierra cuatri-dimensional como un icosaedro (figura geométrica de 20 lados) codificado por las 20 tribus solares; estructura de la Nave del Tiempo Tierra 2013.'),
    ('hol','enc','Índice Armónico','Índice completo de 260 Kin ordenados de acuerdo a cinco células del tiempo y trece trayectorias armónicas; muestra las 65 armónicas de acuerdo con sus pares inversos: utilizado para verificar todas las maniobras de la Brújula y para establecer todas las parejas ocultas y cuartetos y Kin antípodas.'),  
    ('hol','enc','Kin','Pariente, afín, relacionado, igual, Sol y día (en Maya). Cada espacio capaz de tomar diferentes dimensiones en el tiempo afines a los otros restantes 260 Kin. Unidad galáctica de medir, la base de proporciones y las relaciones; un día; uno de las trece unidades de las Ondas Encantadas; cualquier Humano, cualquier umbral galáctico.'),
    ('hol','enc','Kin antípoda','Puntos polares opuestos, relación color rojo/azul, blanco/amarillo, cualesquiera dos sellos solares de colores opuestos dentro de la misma familia Terrestre cuyos números código están separados por diez; en el giro galáctico, cualesquiera dos sellos solares de la misma familia Terrestre, de color opuesto y que tienen el mismo tono galáctico y están separados por 130 Kin o diez Ondas Encantadas.'),
    ('hol','enc','Kin análogo','Relación de color rojo/blanco, azul/amarillo; cualesquier, dos sellos solares cuyos números código suman diecinueve y que son parejas planetarias.'),
    ('hol','enc','Kin oculto','Relación de color azul/blanco, rojo/amarillo; cualesquiera dos sellos solares cuyos números códigos siempre suman 21; en el Oráculo, lo oculto, el elemento inesperado; en el Índice Armónico; los Kin ocultos son cualesquiera dos Kin siguiendo la simetría inversa de las leyes de color ocultas y cuyos tonos galácticos siempre suman catorce.'),
    ('hol','enc','Kin correlativo','Diecinueve constantes de fechas del disco verde de la Brújula Galáctica para convertir el tiempo de tri a cuatri-dimensional; cualquier umbral galáctico correspondiendo a una de estas diecinueve fechas.'),  
    ('hol','enc','Kin planetario','Humano identificado con el umbral galáctico de la fecha de nacimiento; adopta la firma galáctica y vuelve a entrar en la Nave del Tiempo como un activador del holón.'),
    ('hol','enc','Kinich Ahau','Sistema estelar con diez 6rbitas planetarias localizadas en una zona galáctica experimental, foco de colonización de la quinta fuerza galáctica; contiene el potencial para crear el quinto acorde armónico galáctico interdimensional que será entonado en el 2013 d.C.'),
    ('hol','enc','Magia del tiempo transposicional','Habilidad de cambiar posiciones en el tiempo; base de las equivalencias del Kin; base del vuelo mágico y del viaje en el tiempo.'),
    ('hol','enc','Maldek','Nombre del quinto planeta del sistema Kinich Ahau destruido en las “guerras del tiempo” y conocido como el Cinturón de Asteroides.'),
    ('hol','enc','Matriz radial','Estructura y patrón del tiempo cuatri-dimensional; base de sincronía; patrón de pares análogos en el código 0-19; estructura subyacente del índice Armónico.'),
    ('hol','enc','Mesa redonda','Reunión de los Kin planetarios convocados en la corte del Kin; en cualquier Onda Encantada, la cámara de cristal, el tono galáctico 12; lugar de completa igualdad de los Kin planetarios.'),
    ('hol','enc','Nación del Arco Iris','Las cuatro razas cósmicas raíz despertadas con el propósito de lanzar la Nave del Tiempo Tierra 2013; los jugadores del Encantamiento del Sueño que toman  el mandato planetario después del Giro del Tiempo, el 26 de Julio de 1992.'),
    ('hol','enc','Nave del Tiempo Tierra 2013','Vehículo de transporte interdimensional; giro de 26.000 años consistiendo en cinco Castillos codificados por 20 Ondas Encantadas y 260 umbrales galácticos con el propósito de estabilizar el planeta Tierra y el sistema estelar Kinich Ahau.'),
    ('hol','enc','Número de código','Anotación galáctica del punto y la raya, 0-19, que se encuentra en la parte de atrás de las fichas de los sellos solares y en el Tablero del Oráculo.'),  
    ('hol','enc','Onda Encantada','Plantilla del tiempo y módulo de sincronización basado en trece tonos galácticos.'),
    ('hol','enc','Onda Encantada de 26 años','Los últimos 26 años del Encantamiento del Sueño universal de 26.000 años, 1987-2013; organizado como un programa de inversión de la historia de cinco años, campaña de limpieza de ocho años y prueba de conducción de trece años de la Nave del Tiempo Tierra; recapitulan la proporción de evolución 5.8::813.'),
    ('hol','enc','Oráculo del Destino','20 patrones base abriendo los 100 códigos de memoria con el propósito de despertar las cuatro razas cósmicas raíz y las 20 tribus solares de la Nación del Arco Iris.'),
    ('hol','enc','Oráculo del Encantamiento del Sueño','100 patrones del destino como base de la recuperación de la memoria del Génesis galáctico y del papel que juega el Kin planetario para alcanzar la meta del lanzamiento de la Nave del Tiempo Tierra 2013.'),
    ('hol','enc','Parejas planetarias','Sellos solares emparejados de acuerdo al planeta; suma de los sellos emparejados cuyos números código es siempre 19; lo mismo que las parejas o pares de color análogo rojo/blanco, azul/amarillo.'),
    ('hol','enc','Patrón base del destino','Uno de los 20 mandalas de 5 partes, (correspondiendo a las 20 tribus solares) encontrados en el Tablero del Oráculo.'),
    ('hol','enc','Polaridad radial','Principio de simetría inversa que gobierna las relaciones del Kin antípoda en el Tablero de Viaje y del Kin oculto en el Índice Armónico.'),
    ('hol','enc','Portales de activación galácticos','Umbrales a la conciencia galáctica; los 52 umbrales galácticos en trece series de pares de Kin ocultos llamados cuartetos; la suma de los tonos de los 13 cuartetos es 364, o trece Lunas; como el patrón en el Índice Armónico que se conoce como el Telar de las trece Lunas.'),
    ('hol','enc','Pórtico Magnético','Primer tono de cualquier Onda Encantada.'),
    ('hol','enc','Proporción','Razón de relaciones que pueden ser extendidas o expandidas en escala donde la proporción se mantiene constante; en el tiempo cuatri-dimensional siempre está gobernado por el principio de matriz radial.'),
    ('hol','enc','Proporción 12:60','Año de doce meses, hora de 60 minutos del Encantamiento del Sueño de la Historia tridimensional; proporción que Júpiter-Saturno impusieron a la realidad tri-dimensional en la Tierra.'),
    ('hol','enc','Proporción 13:260','20 Ondas Encantadas de trece tonos creando la proporción de la despertada Nave del Tiempo Tierra; revelado a través de la Brújula Galáctica y el Libro del Kin con puntos de acceso universal a los 260 umbrales galácticos del tiempo cuatri-dimensional.'),
    ('hol','enc','Proporción 20:13','Proporción de operación base en la Nave del Tiempo Tierra; 20 tribus solares siguiendo trece Lunas; 20 sellos solares en la proporción de los trece tonos de la Onda Encantada.'),
    ('hol','enc','Provisión acumulada','Créditos de tiempo del holón acumulados durante el Encantamiento del Sueño de la Historia a disposición de los Humanos que se identifiquen como Kin planetarios; para ser descubiertos y utilizados al desarrollar la habilidad de recuperar la memoria del Tablero del Oráculo y el juego de roles del Encantamiento del Sueño.'),
    ('hol','enc','Púlsar','Geometría del tiempo de la Onda Encantada creado por las cuatro constantes de color, creando los cuatro pulsares: la interacción de cuatro pulsares recapitula las cuatro dimensiones - el pulsar del tiempo como la cuarta dimensión, el pulsar de la vida como la primera dimensión, el pulsar de los sentidos como la segunda dimensión y el pulsar de la mente como tercera dimensión.'),
    ('hol','enc','Quinto acorde galáctico','Resonancia armónica de un sistema estelar con el orden galáctico de la quinta fuerza; significa la obtención de la vida universal; próxima entonación que ocurrirá en el 2013 d.C.'),
    ('hol','enc','Ley de la Quinta armónica','En la secuencia de las cuatro constantes de color, el retorno al primer color lleva la quinta armónica y crea una cromática; la ley que determina la codificación de las Familias Terrestres en Ondas Encantadas; base de los púlsares matiz: un punto, tonos 1-6-11, dos puntos, tonos 2-7-12, tres puntos, tonos 3-8-13, cuatro puntos, tonos 4 y 9 y una raya, tonos 5 y 10.'),
    ('hol','enc','Razas cósmicas raíz','Génesis cuatri-dimensional de las razas humanas de acuerdo con el código de color: rojo, blanco, azul, amarillo; base de la rotación de las células del tiempo de las 20 tribus solares; el destino realizado como la Nación del Arco Iris de la Nave del Tiempo Tierra 2013.'),
    ('hol','enc','Quinta fuerza','Factor cromático cuatro mas uno de la circulación del tiempo galáctico; principio de la matriz radial; representado como el Escudo Galáctico en la parte exterior del Tablero de Viaje; el poder organizador quinto dimensional, también conocido como fuerza-g.'),
    ('hol','enc','Sello solar','Impresión icónica de una de las 20 tribus solares.'),
    ('hol','enc','Ley de la Simetría inversa','Principio de la relación radial donde puntos opuestos hacen Espejo unos a otros y el movimiento siempre cruza el centro, también conocido  como  el  principio  de  la  matriz  radial; base del Índice Armónico, código 0-19, y todas las relaciones ocultas donde la unidad de en medio no tiene ni igual ni Espejo, también conocida como la Ley de la Simetría Oculta.'),
    ('hol','enc','Sistema de crédito del Kin','Códigos escondidos dentro del Índice Armónico basado en cuartetos ocultos, créditos basados en armónicas de tonos galácticos construidos a través de la habilidad en descodificar los umbrales galáctico, leer los oráculos del destino y juego de roles del Encantamiento del Sueño.'),
    ('hol','enc','Tablero del Oráculo','Disposición de los 20 patrones base del destino de acuerdo a las cinco células del tiempo, dónde la célula del tiempo de entrada está a la derecha, la célula del tiempo de almacén está arriba, la célula del tiempo del proceso a la izquierda, la célula del tiempo de salida abajo y la célula del tiempo de la matriz en el centro. La disposición de cada célula del tiempo sigue un patrón en contra del sentido del reloj de las constantes de color con rojo en la esquina superior a la derecha, blanco superior izquierda, azul en la inferior izquierda y amarillo en la inferior derecha.'),
    ('hol','enc','Tablero de Viaje','Los cinco castillos de la Nave del Tiempo Tierra que crea las 20 Ondas Encantadas del giro galáctico de 260 Kin, donde el Castillo rojo está a la derecha, el Castillo blanco arriba, el Castillo azul a la izquierda, el Castillo amarillo abajo, y el Castillo verde en el centro; la disposición de las cuatro Ondas Encantadas para cada Castillo sigue un patrón en contra del sentido del reloj, donde la Onda Encantada roja está a la derecha, la Onda Encantada blanca arriba, la Onda Encantada azul a la izquierda y la Onda Encantada amarilla abajo.'),
    ('hol','enc','Tono galáctico','Los trece poderes de la creación; siempre en relación uno con otro, los trece tonos galácticos crean una Onda Encantada.'),
    ('hol','enc','Trayectoria armónica','20 Sellos Solares en la rotación de las cinco células del tiempo desde el Dragón rojo al Sol amarillo; combinados con los trece tonos galácticos crean las trece trayectorias armónicas del Índice Armónico; sigue la Ley de Simetría Inversa estableciendo las seis series de trayectorias Espejo; 1 y 13, 2 y 12, 3 y 11, 4 y 10, 5 y 9, 6 y 8, mientras que la trayectoria 7 no tiene ningún Espejo.'),
    ('hol','enc','Transduce','Función de un transductor o convertidor. Capacidad de tomar una forma de energía o información y cambiarla en otra; el agente de transducción en el ser Humano es el corazón; en el holón del planeta, el núcleo de la Tierra.'),
    ('hol','enc','Transponer','Habilidad de cambiar el valor posicional de los elementos clave; ejemplo: los sellos solares colocados como armónicos cambiados en sellos solares colocados como cromáticas.'),
    ('hol','enc','Tribu Solar','20 agrupaciones de colonizadores galácticos generados por el principio cromático de la quinta fuerza moviéndose a través de los cuatro clanes; también conocido como las 20 tribus del tiempo cuyo propósito es estabilizar las diez alas orbitales de Kinich Ahau.'),
    ('hol','enc','Túnel del tiempo','Eje de la Tierra-Urano pasando a través de los polos de la Tierra al núcleo central; fuente de almacenamiento de la información solar-planetaria, guardada y minada por la Familia Terrestre central; base del cambio de polos 2000; punto de reparación crítica en la célula solar de transbordo intermedio.'),
    ('hol','enc','Umbral galáctico','En la Brújula Galáctica, la combinación de uno de los trece tonos galácticos y los 20 sellos solares, 260 en total; lo mismo que el giro galáctico de los 260 Kin y los 260 mandatos de sincronización del Libro del Kin.'),
    ('hol','enc','Viajar en el tiempo','Habilidad del holón para localizar, recuperar, y divulgar información de acuerdo con las necesidades actuales y representado por el ego tri-dimensional; base del poder del vuelo mágico.'),
    ('hol','enc','Vuelo mágico','Capacidad de conectar Ondas Encantadas, Castillos, giros espectrales y Encantamientos del Sueño; espacio creativamente conectado entre los pórticos cósmicos y magnéticos de dos Ondas Encantadas.')
  ;
  DELETE FROM `_api`.`doc_ide` WHERE `esq`='hol' AND `ide`='enc_cod'; 
  INSERT INTO `_api`.`doc_ide` VALUES
    ('hol','enc_cod','1 Kin','= 1 unidad que puede acomodarse a cualquier equivalencia'),
    ('hol','enc_cod','1 Célula del Tiempo','= 4 sellos solares codificados por el color en sucesión diaria: rojo, blanco, azul y amarillo'),
    ('hol','enc_cod','1 Armónica','= 1 célula del tiempo de 4 Kin codificados por 4 tonos galácticos'),
    ('hol','enc_cod','65 Armónicas','= 1 giro galáctico de 260 Kin'),
    ('hol','enc_cod','5 Células del tiempo','= 1 trayectoria armónica = 20 sellos solares, en la sucesión Dragón - Sol = 20 Kin'),
    ('hol','enc_cod','13 Trayectorias armónicas','= 1 giro galáctico de 260 Kin'),
    ('hol','enc_cod','1 Onda Encantada','= 13 Kin codificados por los 13 tonos galácticos'),
    ('hol','enc_cod','20 Ondas Encantadas','= 1 giro galáctico de 260 Kin'),
    ('hol','enc_cod','4 Ondas Encantadas','= 1 Castillo = 52 Kin'),
    ('hol','enc_cod','5 Castillos','= 1 giro galáctico de 260 Kin'),
    ('hol','enc_cod','13 armónicas','= 1 castillo'),
    ('hol','enc_cod','1 Cromática','= 5 Kin'),
    ('hol','enc_cod','1 estación galáctica','= 13 cromáticas = 65 Kin'),
    ('hol','enc_cod','1 giro espectral','= 4 estaciones galácticas = 52 cromáticas = 260 Kin'),
    ('hol','enc_cod','1 semana','= 7 Kin = 1/4 de Luna'),
    ('hol','enc_cod','4 semanas','= 1 Luna = 28 Kin'),
    ('hol','enc_cod','13 semanas','= 1/4 de año solar'),
    ('hol','enc_cod','52 semanas','= 364 Kin = 1 año solar menos 1 día'),
    ('hol','enc_cod','1 Luna','= 28 Kin'),
    ('hol','enc_cod','13 lunas','= 364 Kin'),
    ('hol','enc_cod','13 lunas + 1 día verde','= 365 Kin = 1 año solar'),
    ('hol','enc_cod','7 giros galácticos','= 1.820 Kin = 1 holkin = 5 años solares menos 5 días'),
    ('hol','enc_cod','36,5 giros galácticos','= 26 años solares = 9.490 Kin'),
    ('hol','enc_cod','52 años solares','= 73 giros galácticos = 18.980 Kin')
  ;
  DELETE FROM `_api`.`doc_ide` WHERE `esq`='hol' AND `ide`='enc_nav';
  INSERT INTO `_api`.`doc_ide` VALUES
    ('hol','enc_nav','HOLON','La totalidad galáctica, caracterizado por la consistencia integral, la capacidad de auto-organizarse, y la inclusividad multidimensional; la estructura cuatri-dimensional del tiempo, representado como un tetraedro; un subconjunto y cualquiera de sus partes dentro de la totalidad galáctica.'),
    ('hol','enc_nav','FRACTAL','Una gama de frecuencia que mantiene una simetría a lo largo de una escala; la proporción del holón dentro de un holón mayor que siempre recapitula la totalidad.'),
    ('hol','enc_nav','HOLONÓMICO','La cualidad de la autonomía fractal que refleja y mantiene la totalidad.'),
    ('hol','enc_nav','HOLONOMIA','La ciencia y las leves que gobiernan el principio fractal del holón.'),
    ('hol','enc_nav','SINTROPÍA','Ley por la cual holones autónomos se atraen y giran juntos para crear totalidades cada vez más grandes, el opuesto de entropía.'),
    ('hol','enc_nav','ENTROPÍA','Función de un sistema cerrado de la distorsión del tiempo tri-dimensional caracterizado por la disipación de energía, el sistema entrópico está gobernado por leyes que disminuyen la autonomía de los fractales, en el reino humano la entropía tiene corno resultado una civilización de materialismo autodestructivo.'),
    ('hol','enc_nav','FUERZA-G','Tiempo galáctico cuatri-dimensional como la quinta tuerza, el principio de unión fractal del holón; el rayo de sincronización radial del tiempo galáctico; la rueda dentada matiz que une y armoniza las dimensiones.'),
    ('hol','enc_nav','CÓDIGO DE FRECUENCIA GALÁCTICA','Proporción 1:13 gama de trece fre-cuencias cada una representando una magnitud y una función de la totalidad galáctica; la plantilla de trece unidades recapitulando la cosmología del holón; código de anotación binaria de punto y raya recombinante de trece unidades; planilla de la forma de onda del giro galáctico, u Onda Encantada.'),
    ('hol','enc_nav','CÓDIGO PUNTO-RAYA','Sistema de anotación galáctico en secuencia de 1 a 4 puntos y una barra representando 5 ó 0; base del código matemático del fractal galáctico con cualidades de ser: Holográfico, binario, acumulativo, recombinante, secuencial, vigesimal y posicional.'),
    ('hol','enc_nav','CÓDIGO CROMÁTICO','Código primario donde los números 1 a 4 están representados por un número correspondiente de puntos y el número 5 por una raya; el intervalo del 4º al 5º es 1a base del matiz cromático; el código cromático avanza el color en una secuencia primaria donde, rojo = 1 punto, blanco = 2 puntos, azul = 3 puntos, amarillo = 4 puntos; como la síntesis del azul y el amarillo, el verde es el 5º, la raya, que trae el matiz.'),
    ('hol','enc_nav','ECUACIÓN FRACTAL DE LA FUERZA-G:','5:8::8:13 describe la relación del código cromático del 5 con el código de la frecuencia galáctica del 13; las unidades 5, 8 y 13 forman un conjunto en la serie de espirales logarítmicas; la diferencia entre el código cromático del 5 y el código de la frecuencia galáctica del 13 es la armónica galáctica del 8; el código cromático del 5 combinado con el código de la fuerza-g del 13 es la base del giro galáctico.'),
    ('hol','enc_nav','FORMA DE ONDA','Fractal del holón de trece kin, proporción de 1:20 del giro galáctico; cuatro ondas del tiempo crean un fractal-g de 52 kin, también conocido como la Onda Encantada de trece tonos.'),
    ('hol','enc_nav','KIN','Unidad de medida fractal, un kin por gama de frecuencia galáctica, trece kin por forma de onda: un día solar terrestre, 260 por giro galáctico; holón humano galácticamente unido.'),
    ('hol','enc_nav','FRACTAL-G','Formas de cuatro ondas. Fractal de 52 kin del holón el cual coordina las permutaciones de las trece gamas de frecuencia y de los cuatro colores de códigos primarios (rojo, blanco, azul, amarillo) en una secuencia no variable: cinco por giro galáctico; uno en una proporción 1:7 = un año solar; uno en una proporción 1:5 = un fractal maestro de los cuatro espectros del ser galáctico.'),
    ('hol','enc_nav','20 SELLOS SOLARES','Código cromático de punto y raya de cinco combinado con los cuatro colores de código primario crean 20 frecuencias solares, cada una definida como un sello icono; no variable en secuencia, ciclo de 20 kin de cinco células del tiempo combinan con trece gamas de frecuencia para crear un giro galáctico. '),
    ('hol','enc_nav','GIRO GALÁCTICO','la secuencia de 260 kin entrelaza los 365 días del año solar precisamente cada 52 años solares; proporción de giros con los años solares 7: 5; 7 giros galácticos = 5 años solares; 36,5 giros galácticos = 26 años solares, 73 giros galácticos 52 años solares.'),
    ('hol','enc_nav','CALENDARIO GALÁCTICO','Plantilla del giro galáctico de 260 kin; 13 frecuencias galácticas codificadas por 20 sellos solares; 5 fractales galácticos; 20 formas de onda; 52 cromáticas de 5 kin; 65 armónicas de células de tiempo de 4 días; 4 espectros de 65 kin.'),
    ('hol','enc_nav','CÉLULA DE TIEMPO','Secuencia de 4 kin codificada por 4 colores primarios; 5 células de tiempo acomodan la secuencia de 20 sellos solares; 65 armónicas de células de tiempo por giro galáctico.'),
    ('hol','enc_nav','CROMÁTICA','Una de las cuatro secuencias de 5 kin que comienza con el grupo raya- cinco que termina con el mismo color de kin. Las cromáticas codifican los cuatro espec- tros del ser galáctico de 65 kin; las 52 cromáticas conectan: las armónicas de células de tiempo, las formas de onda, las fractales-g y los giros galácticos.'),
    ('hol','enc_nav','ESPECTROS','Código de 65 kin de tres secuencias de 20 kin y uno de 5 kin sintoniza- do con las cromáticas raya cinco; cuatro giros galácticos del matiz del código de cuatro colores primarios de fractal-g se entrelazan; base de la proporción 1:5 del fractal maestro; funcionan como fractales tractor que traen el tiempo tri-dimensional al tiempo cuatri- dimensional.'),
    ('hol','enc_nav','ARMÓNICA','Célula de tiempo de 4 kin codificada por una de las trece frecuencias galácticas; 13 armónicas por fractal-g, 5 fractales-g = 65 armónicas por giro galáctico.'),
    ('hol','enc_nav','TIEMPO GALÁCTICO','Matriz de la cuarta dimensión informando a la tercera di-mensión a través de las armónicas fractales.'),
    ('hol','enc_nav','MATRIZ','Regla del holón donde cada proporción fractal o Kin lleva un valor igual, sobrexcede cualquier regla o ley tri-dimensional no consistente con la proporción de equivalencia de todos los Kin; 5º célula de tiempo y 5º fractal-g del giro galáctico conteniendo los matices de la cromática raya-cinco.'),
    ('hol','enc_nav','SOL','Receptor-transmisor local de la fuerza-g cuatri-dimensional; base de la red de 20 sellos solares uniendo el cuerpo cuatri-dimensional del planeta Tierra, u holón planetario.'),
    ('hol','enc_nav','HOLON SOLAR','Receptor-transmisor local de la fuerza-g cuatri-dimensional; base de la red de 20 sellos solares uniendo el cuerpo cuatri-dimensional del planeta Tierra, u holón planetario.'),
    ('hol','enc_nav','RED PLANETARIA','Sistema de diez planetas en relación con la estrella local, el sol, orbitalmente unidos por dos sellos solares cada uno, uno para la entrada galáctica, otro para la salida solar.'),
    ('hol','enc_nav','FAMILIA PLANETARIA','Cinco familias planetarias, corresponden a la colocación del código cromático 1:5 de los 20 sellos solares; cada familia planetaria consiste en cuatro sellos solares que recapitulan el código de cuatro colores primarios, la fecha de nacimiento determina la familia planetaria: cualquier cumpleaños solar se mueve a través de cuatro sellos solares de una familia planetaria combinado cor las trece frecuencias galácticas en un periodo de 52 años, las cinco familias planetarias corresponden a la forma de la red del holón planetario, también conocida como familia Terrestre.'),
    ('hol','enc_nav','HOLON PLANETARIO','La estructura cuatri-dimensional de la Nave del Tiempo Tie- rra: codificada horizontalmente por las cinco familias planetarias; codificadas diagonalmente desde el polo norte al polo sur, del oeste al este, como las cuatro cromáticas de 5 Kin; codificadas diagonalmente desde el polo norte al polo sur, del este al oeste, como las cuatro familias de color de 5 Kin; estos tres códigos actúan como el giroscopio del holón planetario del tiempo galáctico.'),
    ('hol','enc_nav','LA NAVE DEL TIEMPO TIERRA','El planeta Tierra en su órbita, creando la cuarta dimensión que encierra en sí la tercera.'),
    ('hol','enc_nav','LA DISTORSIÓN DEL TIEMPO','Un sistema cerrado tri-dimensional gobernado por un calendario patriarcal no circulante de 12 meses, condición donde la entropía, el mate- rialismo, y la civilización son una y la misma función.'),
    ('hol','enc_nav','MATERIALISMO','Creencia en un marco exclusivamente tri-dimensional que se mira a sí mismo por la sobreexplotación del plano físico; creencia de que el tiempo es una función del espacio que sella la distorsión del tiempo.'),
    ('hol','enc_nav','CIVILIZACIÓN','Dominación patriarcal operando en un marco de 12 meses sin tornar en cuenta la matriz: proceso de creciente dominación y separación del orden natural.'),
    ('hol','enc_nav','MECANIZACIÓN','Etapa Final de la civilización dónde el materialismo es mecaniza- do por la fórmula “el tiempo es dinero”, que permite extensa inversión entrópica de valores y la degradación planetaria.'),
    ('hol','enc_nav','GIRO DEL TIEMPO','Liberación de la distorsión del tiempo tri-dimensional para en- trar en el tiempo galáctico cuatri-dimensional.'),
    ('hol','enc_nav','PLANTILLA DE CONVERSIÓN','Calendario Terrestre solar lunar de trece meses de 28 días, más un día verde circulante, sincronizado con el calendario solar-galáctico y el giro galáctico; ocho secuencias codificadas de color del calendario Terrestre solar-lunar yendo desde el 26 de julio de l992 hasta el 25 de julio de 2000.'),
    ('hol','enc_nav','ARTE PLANETARIO','Kin humano galácticamente unido, interactuando de acuerdo a la red de frecuencia del holón planetario y de las familias planetarias; simbiosis del holón cuatri-dimensional humano Terrestre con el holón planetario.'),
    ('hol','enc_nav','ESPORA DEL ARTE PLANETARIO','Florecimiento del ciclo evolucionario humano de 26.000 años; fruto del giro del tiempo y de la exploración de la cuarta dimensión; la Nave del Tiempo Tierra 2013.'),
    ('hol','enc_nav','LIBRE VOLUNTAD','Movimiento sintrópico del fractal del holón hacia una autonomía auto-regulada y una mayor interdependencia con otros holones; base del arte planetario.'),
    ('hol','enc_nav','QUINTA FUERZA','Matiz Entonada que contiene el centro; unidad posicional en un código matemático que permite completo potencial armónico; el tiempo como una matriz radial interdimensional que engrana con la fuerza-g.'),
    ('hol','enc_nav','CUARTA DIMENSIÓN','El tiempo como plano del ser todo inclusivo, y no físico; inteligencia de orden continuo del ser galáctico.'),
    ('hol','enc_nav','TERCERA DIMENSIÓN','El espacio como plano físico del ser; forma manifestada del orden natural; campo evolucionario del ser galáctico; inseparable de la cuarta dimensión.'),
    ('hol','enc_nav','FRACTAL DE 26 AÑOS','Período entre 1987 y 2013 dividido en dos formas de Onda de trece años; recapitula el ciclo evolucionario humano de 26.000 años donde la historia es invertida en la primera forma de Onda de 13 años, y la prehistoria se recicla en el tiempo galáctico en la segunda forma de onda de 13 años; el fractal galáctico 26 define los ciclos evolucionarios.'),
    ('hol','enc_nav','SECUENCIA BIOCROMATICA','Internalización del código cromático del holón humano que se expande a lo largo del ciclo cromático de 5 Kin; base para identificar el vínculo del Kin humano con la red del holón planetario.')    
  ;
  -- de las 13 lunas en movimiento
  DELETE FROM `_api`.`doc_ide` WHERE `esq`='hol' AND `ide` LIKE 'lun%';
  INSERT INTO `_api`.`doc_ide` VALUES
    ('hol','lun','Inhalar','10 kin (secuencia de sellos solares Sol-Luna) pueden ser iguales a 10 días, que es la mitad de una trayectoria armónica, 10 años que es la mitad de un katún, o 10 Katunes que es la mitad de una baktun.'),
    ('hol','lun','Exhalar','10 kin (secuencia de sellos solares Perro-Tormenta) pueden ser iguales a 10 días, que es la mitad de una trayectoria armónica, 10 años que es la mitad de un katún, o 10 Katunes que es la mitad de una baktun.'),
    ('hol','lun_cod','Código de Color','Cuatro frecuencias de color: rojo, blanco, azul, amarillo Quinta frecuencia entonada: Verde.'),
    ('hol','lun_cod','Código Solar','Cuatro colores en movimiento por el quinto entonado crean las 20 frecuencias solares, representadas por los 20 sellos solares o iconos. Estos también están representadas en la notación de punto y barra como el código 0-19, base de toda la Matemática numérica completa de los Mayas.'),
    ('hol','lun_cod','Código Galáctico','Trece tonos galácticos que constituyen la forma constante de la Onda Encantada de 13 kin.'),
    ('hol','lun_dia','Armónica','Cuatro días (cuatro kin: rojo blanco, azul, amarillo) 65 armónicas por giro galáctico.'),
    ('hol','lun_dia','Cromática','Cinco días (cinco kin: cualquiera de los cuatro juegos del kin polar al portal) 52 cromáticas por giro galáctico.'),
    ('hol','lun_dia','Semana, Heptada','Siete días (siete kin: Dali hasta Silio) 52 semanas/heptadas por año solar-lunar.'),
    ('hol','lun_dia','Onda Encantada','Trece kin: tonos galácticos del uno al trece. 20 ondas encantadas por giro galáctico.'),
    ('hol','lun_dia','Trayectoria Armónica (Fractal del Baktun de los Mayas)','20 kin (secuencia de sellos solares del Dragón al Sol) Trece trayectorias armónicas por giro galáctico.'),
    ('hol','lun_dia','Correlación de las Fechas (Fractal del Uinal Maya)','Secuencia de 20 kin para marcar el año solar-lunar al giro galáctico (anillo verde de la brújula galáctica) 18 por año solar-lunar más una secuencia de cinco kin, de Julio 21 al 25 (Uayeb Maya).'),
    ('hol','lun_dia','Luna','28 días (28 kin) de cuatro semanas cada una), 13 lunas por año solar-lunar más un día verde, Julio 25.'),
    ('hol','lun_dia','Castillo','52 días (52 kin) de cuatro ondas encantadas codificadas por el color, roja, blanca, azul, amarilla. Cinco castillos por giro galáctico.'),
    ('hol','lun_dia','Espectro Galáctico','65 días (65 kin) de trece cromáticas cada: Espectro galáctico rojo, espectro galáctico blanco, espectro galáctico azul, espectro galáctico amarillo. Cuatro espectros galácticos por giro galáctico (Código Maya de los días del quemador).'),
    ('hol','lun_dia','Giro Galáctico','260 días (260 kin) 20 ondas encantadas, 65 armónicas, 52 cromáticas, 4 castillos, 4 espectros galácticos (Tzolkin Maya).'),
    ('hol','lun_dia','Año solar-Lunar','365 días (365 Kin) de 13 lunas, 52 semanas más un día verde.'),
    ('hol','lun_cic','Ciclo de Retomo Armónico','Cuatro años solares-lunares medidos desde cualquier evento significante, por ejemplo, un cumpleaños o cualquier sincronización solar-galáctica la cual siempre es Julio 26. Trece trayectorias armónicas por ciclo solar-galáctico de 52 años.'),
    ('hol','lun_cic','Holtun','Cinco años solares-lunares de forma precisa igual que siete giros galácticos menos cinco días (1820 kin).'),
    ('hol','lun_cic','Octava Lunar','Ocho años solar-lunares, precisamente igual que cinco giros de Venus (584 días cada uno) 104 lunas (28 días o kin) y 100 Lunaciones (29,20 días) para un total de 2920 kin.'),
    ('hol','lun_cic','Retomo Galáctico','Trece años solar-lunares (una octava lunar más un holtun) medidos desde cualquier evento significante, por ejemplo, un cumpleaños o cualquier sincronización solar- galáctica la cual siempre es Julio 26. Cuatro retornos galácticos por ciclo de 52 años.'),
    ('hol','lun_cic','Katun Maya (Marcador)','20 años solar-lunares (cuatro holtun, cinco retornos armónicos). 260 katún por el gran ciclo de 4.200 años.'),
    ('hol','lun_cic','Ciclo de Retomo solar-Galáctico','Sincronización precisa de 52 años solar-lunares con 73 giros galácticos. Trece retornos armónicos y cuatro retornos galácticos (18.980 Kin).'),
    ('hol','lun_cic','Cromática o Quinto Galáctico','65 años solar-lunares o cinco retornos galácticos de 13 años.'),
    ('hol','lun_cic','Hexa o Sexto Galáctico','78 años solar-lunares o seis retornos galácticos de 13 años.'),
    ('hol','lun_cic','Séptimo Galáctico','91 años solar-lunares o siete ciclos galácticos de 13 años.'),
    ('hol','lun_cic','Siglo','100 años solar-lunares, cinco katún, 20 holtun, 25 retornos armónicos.'),
    ('hol','lun_cic','Coro Arcturiano u Octava Galáctica','104 años solar-lunares, ocho retornos galácticos, trece octavas lunares, 26 retornos armónicos, 65 giros de Venus (37.960 Kin).'),
    ('hol','lun_cic','Gran Katún (Katún Ahau de los Mayas)','260 años solar-lunares, trece katunes, 20 por el gran ciclo.'),
    ('hol','lun_cic','Baktun','400 años solar-lunares del Encantamiento del Sueño, 20 katunes, trece por Gran Ciclo.'),
    ('hol','lun_cic','Milenio','10 siglos de 50 Katún, 200 Holtun, 1.000 años solar-lunares, 26 por año Pleyadiano.'),
    ('hol','lun_cic','Gran Ciclo','5.200 años solar-lunares del Encantamiento del Sueño, trece Baktun, 260 Katún, cinco por año Pleyadiano.'),
    ('hol','lun_cic','Año Pleyadiano','26.000 años solar-lunar del Encantamiento del Sueño, 260 siglos del Encantamiento del Sueño, cinco Gran Ciclos, lo mismo que un Encantamiento del Sueño Planetario, cuatro por intervalo de Hunab Ku.'),
    ('hol','lun_cic','Intervalo de Hunab Ku','104.000 años solar-lunares del Encantamiento del Sueño, 20 Gran Ciclos, 260 baktun, cuatro años Pleyadianos.')
  ;
  -- del Telektonon 
  DELETE FROM `_api`.`doc_ide` WHERE `esq`='hol' AND `ide`='tel';
  INSERT INTO `_api`.`doc_ide` VALUES       
    ('hol','tel','Baktun','Cuenta de 144.000 Kin 0 días; la cuenta de trece Baktunes es la medida del ciclo de la historia desde 3113 AC hasta 2012 DA.'),
    ('hol','tel','Biosfera','Frágil membrana planetaria de vida y su sistema de apoyo inorgánico diseminado sobre la superficie de la Tierra; zona de experimento de la libre voluntad de las Guerras del Tiempo que ahora está amenazada por la civilización 12:60 del materialismo del Planeta Babilónico; ver también Noosfera.'),
    ('hol','tel','Bolon Ik','Amante celestial de Pacal Votan quien teje la visión del viaje en el Laberinto del Guerrero desde su torre de la Navegación en Urano. Bolon Ik significa "Viento Solar Blanco".'),
    ('hol','tel','Bolon Tiku','Invocación del poder del nueve: los nueve señores del Tiempo y el Destino quienes gobiernan el poder del tiempo en el inconsciente.'),
    ('hol','tel','Cronometría, cronométrico','Medida 13:20 del tiempo tridimensional; ciencia que mide el tiempo biotelepáticamente; aplicado como el esquema de cartas del Telektonon del Cronómetro Diario Universal.'),
    ('hol','tel','Cubo de la Ley','Ver Ley del Cubo'),
    ('hol','tel','Federación Galáctica','La más alta organización de inteligencia dimensional,  responsable de supervisar el experimento de la libre voluntad tridimensional, ahora localizado en el Planeta Tierra.'),
    ('hol','tel','Haab','Órbita planetaria medida por 18 ciclos de 20 días más el Vayeb de 5 días. Heptágono de la Mente: Cubo cuatridimensional de poder del Siete para ser recobrado durante los siete años de profecía, 1993-2000; lo mismo que la transición Biosfera- Noosfera; la realización de la mente, voluntad y espíritu colectivos de la raza humana organizada bajo una frecuencia correcta de tiempo 13:20.'),
    ('hol','tel','Hunab Ku','Único Dador de Movimiento y Medida; término galáctico Maya para Dios o Alá.'),
    ('hol','tel','Iblis','Nombre del Angel disidente de la creación; también conocido como Satán; poder ilusorio del ego humano en todas sus formas.'),
    ('hol','tel','Katun','Cuenta de 7200 Kin o días, 20 por Baktun; algo más que los diecinueve años solares, una generación humana.'),
    ('hol','tel','Kin del Destino','Nombre de la posición diaria de acuerdo al giro Galáctico de 260 Kin, Kin central del oráculo de la Quinta Fuerza.'),
    ('hol','tel','Kinich Ahau','Nombre galáctico Maya para nuestro sol y su sistema planetaria; el sistema solar todo como un ser.'),
    ('hol','tel','Kuxan Suum','Carretera, que alcanza a las raíces de las estrellas, pasando a través de cada una de las dimensiones celestiales; las fibras etéricas que conectan el plexo solar con el centro de la galaxia; "el ombligo de Hunab Ku".'),
    ('hol','tel','Ley del Cubo','Intersección de los tres planos: el plano de la mente, el plano del espíritu y el plano de la voluntad que ubica toda manifestación bajo el gobierno de una ley interdimensional divina, cubierta por la falsa autoridad 12:60 de la Torre de Babel, redimida por el Viaje de la Inteligencia en el Laberinto del Guerrero de 16 días: también conocida como el Cubo de la Ley.'),
    ('hol','tel','Luna','Ciclo menstrual femenino de 28 días y ciclo biológico humano, trece por cada órbita planetaria anual; base del Calendario de 13 Lunas y regreso de la humanidad al orden natural.'),
    ('hol','tel','Maya','Nombre dado a la civilización en América Central cuyo Período Clásico corresponde al décimo ciclo Baktun. 435-830 DA navegantes galácticos del tiempo.'),
    ('hol','tel','Noosfera','La cubierta mental telepática que rodea al planeta como resultado del @toso seguimiento del Calendario de las 13 lunas durante los siete años de profecía, referido también como la Transición Biosfera-Noosfera y la completación del Heptágono de la Mente asegurando el retorno del Cubo de la Ley.'),
    ('hol','tel','Notación Galáctica','Sistema de cuentas Maya del punto y barra, de código del 0 al 19; también código de trece unidades de la onda encantada del tiempo cuatridimensional que además gobierna el ciclo de trece lunas.'),
    ('hol','tel','Onda Encantada','Nombre dado a los trece tonos galácticos que gobiernan cada uno de los 20 ciclos de 13 días del giro galáctico de 260 días, así como del ciclo anual del Calendario de Trece Lunas.'),
    ('hol','tel','Onda Encantada del Servicio Planetario','Ciclo de las Trece Lunas organizado por los cuatro pulsares del tiempo cuatridimensional.'),
    ('hol','tel','Oráculo de la Quinta Fuerza','Conjunto de relaciones constantes mantenidas por el Kin del Destino; usado en el Telektonon para seguir la pista de las intersecciones diarias del tiempo y leer el Oráculo de las Siete Generaciones.'),
    ('hol','tel','Oxlahun Tiku','Invocación para convocar el poder del trece, el poder consciente del tiempo; se refiere también al Universo trece dimensional.'),
    ('hol','tel','Pacal Votan','Testigo especial del tiempo: revelador del Cubo de la Ley y de "La Piedra Parlante de la Profecía"-, tiempo de su poder: 631-683 DA.'),
    ('hol','tel','Palenque','Lugar del Templo Sagrado; trono del poder terrenal de Pacal Votan; también conocido como Nah Lugar de la Serpiente, ubicado en Chiapas, México.'),
    ('hol','tel','Planeta Babilónico','Nombre dado a la civilización moderna de materialismo exclusivo; la mente humana capturada por la frecuencia de tiempo 12:60; corresponde al decimotercer Baktun, 1618-2012 DA; para ser redimido por el Telektonon.'),
    ('hol','tel','Poderes de los Números Telecósmicos','Cuatro poderes celestiales en la forma de números: nueve, trece, cinco y cuatro, los que Bolon Ik usa para dar poder a los campos de consciencia y ayudar a Pacal Votan durante su Caminata en la Tierra.'),
    ('hol','tel','Pulsares','Geometría cuatridimensional del tiempo que sincroniza la onda encantada de trece unidades, de acuerdo a las cuatro funciones dimensionales; tiempo, vida, sentido y mente.'),
    ('hol','tel','Sincronometría, sincronométrico','Medida de sincronicidad; ciencia cuatridimensional para practicar la telepatía, aplicada como movimiento diario de piezas del juego en el Tablero del Telektonon.'),
    ('hol','tel','Telektonon','Tubo por el que Habla el Espíritu de la Tierra; canal de comunicación simbólico; la Piedra Parlante de la Profecía. Es la revelación de que el Calendario de Trece Lunas es el camino de la realización humana y el triunfo de la telepatía universal. Nombre de Bendición recibido por aquellos que conocen a fondo la Ley del Cubo.'),
    ('hol','tel','Telepatía','Poder cuatridimensional de inteligencia para la unificación de las especies tridimensionales en la forma de arte planetaria.'),
    ('hol','tel','Torre de Babel','Nombre dado al poder del tiempo falso desde el comienzo de  la historia (Baktun 1, año 3113 AC); base del Planeta Babilónico.'),
    ('hol','tel','Tzolkin','Calendario sagrado de los Maya: medida cuatridimensional del tiempo galáctico; giro galáctico de 260 Kin; módulo armónico.')
  ;
  -- de la Sonda de Arcturus 
  DELETE FROM `_api`.`doc_ide` WHERE `esq`='hol' AND `ide`='arc';
  INSERT INTO `_api`.`doc_ide` VALUES
    ('hol','arc','',''),
    ('hol','arc','','')
  ;